{{- if include "claimctl.isManagedDatabaseSecret" . }}
{{- $user := ternary .Values.postgres.userDatabase.user.value .Values.db.user .Values.postgres.enabled }}
{{- $password := ternary .Values.postgres.userDatabase.password.value .Values.db.password .Values.postgres.enabled }}
{{- $name := ternary .Values.postgres.userDatabase.name.value .Values.db.name .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "claimctl.databaseSecretName" . }}
  labels:
    {{- include "claimctl.labels" . | nindent 4 }}
type: Opaque
data:
  db-user: {{ $user | b64enc | quote }}
  db-password: {{ $password | b64enc | quote }}
  db-name: {{ $name | b64enc | quote }}
{{- end }}