// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: api_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO claimctl.api_tokens (user_id, name, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, token_hash, created_at, expires_at, last_used_at
`

type CreateAPITokenParams struct {
	UserID    uuid.UUID          `json:"userId"`
	Name      string             `json:"name"`
	TokenHash string             `json:"tokenHash"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ClaimctlApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i ClaimctlApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, user_id, name, token_hash, created_at, expires_at, last_used_at FROM claimctl.api_tokens
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ClaimctlApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, tokenHash)
	var i ClaimctlApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, user_id, name, token_hash, created_at, expires_at, last_used_at FROM claimctl.api_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAPITokens(ctx context.Context, userID uuid.UUID) ([]ClaimctlApiToken, error) {
	rows, err := q.db.Query(ctx, listAPITokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimctlApiToken
	for rows.Next() {
		var i ClaimctlApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :exec
DELETE FROM claimctl.api_tokens
WHERE id = $1 AND user_id = $2
`

type RevokeAPITokenParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) error {
	_, err := q.db.Exec(ctx, revokeAPIToken, arg.ID, arg.UserID)
	return err
}

const updateAPITokenLastUsed = `-- name: UpdateAPITokenLastUsed :exec
UPDATE claimctl.api_tokens
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateAPITokenLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAPITokenLastUsed, id)
	return err
}
