// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: audit_logs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO claimctl.audit_logs (
    actor_id,
    action,
    entity_type,
    entity_id,
    changes,
    ip_address,
    created_at
) VALUES (
             $1, $2, $3, $4, $5, $6, EXTRACT(EPOCH FROM NOW())::BIGINT
         )
RETURNING id, actor_id, action, entity_type, entity_id, changes, ip_address, created_at
`

type CreateAuditLogParams struct {
	ActorID    pgtype.UUID `json:"actorId"`
	Action     string      `json:"action"`
	EntityType string      `json:"entityType"`
	EntityID   pgtype.Text `json:"entityId"`
	Changes    []byte      `json:"changes"`
	IpAddress  pgtype.Text `json:"ipAddress"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (ClaimctlAuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ActorID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Changes,
		arg.IpAddress,
	)
	var i ClaimctlAuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Changes,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditLogs = `-- name: GetAuditLogs :many
SELECT a.id, a.actor_id, a.action, a.entity_type, a.entity_id, a.changes, a.ip_address, a.created_at, u.email as actor_email
FROM claimctl.audit_logs a
LEFT JOIN claimctl.users u ON a.actor_id = u.id
ORDER BY a.created_at DESC
LIMIT $1 OFFSET $2
`

type GetAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetAuditLogsRow struct {
	ID         uuid.UUID   `json:"id"`
	ActorID    pgtype.UUID `json:"actorId"`
	Action     string      `json:"action"`
	EntityType string      `json:"entityType"`
	EntityID   pgtype.Text `json:"entityId"`
	Changes    []byte      `json:"changes"`
	IpAddress  pgtype.Text `json:"ipAddress"`
	CreatedAt  int64       `json:"createdAt"`
	ActorEmail pgtype.Text `json:"actorEmail"`
}

func (q *Queries) GetAuditLogs(ctx context.Context, arg GetAuditLogsParams) ([]GetAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, getAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAuditLogsRow
	for rows.Next() {
		var i GetAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Changes,
			&i.IpAddress,
			&i.CreatedAt,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
