// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: groups.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addSpacePermission = `-- name: AddSpacePermission :exec
INSERT INTO claimctl.space_permissions (
    space_id, group_id, user_id
) VALUES (
    $1, $2, $3
)
ON CONFLICT DO NOTHING
`

type AddSpacePermissionParams struct {
	SpaceID pgtype.UUID `json:"spaceId"`
	GroupID pgtype.UUID `json:"groupId"`
	UserID  pgtype.UUID `json:"userId"`
}

func (q *Queries) AddSpacePermission(ctx context.Context, arg AddSpacePermissionParams) error {
	_, err := q.db.Exec(ctx, addSpacePermission, arg.SpaceID, arg.GroupID, arg.UserID)
	return err
}

const addUserToGroup = `-- name: AddUserToGroup :exec
INSERT INTO claimctl.group_members (
  group_id, user_id
) VALUES (
  $1, $2
)
ON CONFLICT DO NOTHING
`

type AddUserToGroupParams struct {
	GroupID uuid.UUID `json:"groupId"`
	UserID  uuid.UUID `json:"userId"`
}

func (q *Queries) AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error {
	_, err := q.db.Exec(ctx, addUserToGroup, arg.GroupID, arg.UserID)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO claimctl.groups (
  name, description
) VALUES (
  $1, $2
)
RETURNING id, name, description, created_at, updated_at
`

type CreateGroupParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (ClaimctlGroup, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.Name, arg.Description)
	var i ClaimctlGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM claimctl.groups
WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, description, created_at, updated_at FROM claimctl.groups
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGroup(ctx context.Context, id uuid.UUID) (ClaimctlGroup, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i ClaimctlGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupByName = `-- name: GetGroupByName :one
SELECT id, name, description, created_at, updated_at FROM claimctl.groups
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetGroupByName(ctx context.Context, name string) (ClaimctlGroup, error) {
	row := q.db.QueryRow(ctx, getGroupByName, name)
	var i ClaimctlGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSpacePermissions = `-- name: GetSpacePermissions :many
SELECT sp.id, sp.space_id, sp.group_id, sp.user_id, sp.created_at,
       g.name as group_name,
       u.email as user_email
FROM claimctl.space_permissions sp
LEFT JOIN claimctl.groups g ON sp.group_id = g.id
LEFT JOIN claimctl.users u ON sp.user_id = u.id
WHERE sp.space_id = $1
`

type GetSpacePermissionsRow struct {
	ID        uuid.UUID          `json:"id"`
	SpaceID   pgtype.UUID        `json:"spaceId"`
	GroupID   pgtype.UUID        `json:"groupId"`
	UserID    pgtype.UUID        `json:"userId"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	GroupName pgtype.Text        `json:"groupName"`
	UserEmail pgtype.Text        `json:"userEmail"`
}

func (q *Queries) GetSpacePermissions(ctx context.Context, spaceID pgtype.UUID) ([]GetSpacePermissionsRow, error) {
	rows, err := q.db.Query(ctx, getSpacePermissions, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpacePermissionsRow
	for rows.Next() {
		var i GetSpacePermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.GroupID,
			&i.UserID,
			&i.CreatedAt,
			&i.GroupName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGroups = `-- name: GetUserGroups :many
SELECT g.id, g.name, g.description, g.created_at, g.updated_at
FROM claimctl.groups g
JOIN claimctl.group_members gm ON g.id = gm.group_id
WHERE gm.user_id = $1
`

func (q *Queries) GetUserGroups(ctx context.Context, userID uuid.UUID) ([]ClaimctlGroup, error) {
	rows, err := q.db.Query(ctx, getUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimctlGroup
	for rows.Next() {
		var i ClaimctlGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT u.id, u.email, u.name, u.role
FROM claimctl.users u
JOIN claimctl.group_members gm ON u.id = gm.user_id
WHERE gm.group_id = $1
`

type ListGroupMembersRow struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
	Name  string    `json:"name"`
	Role  string    `json:"role"`
}

func (q *Queries) ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersRow
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, description, created_at, updated_at FROM claimctl.groups
ORDER BY name
`

func (q *Queries) ListGroups(ctx context.Context) ([]ClaimctlGroup, error) {
	rows, err := q.db.Query(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimctlGroup
	for rows.Next() {
		var i ClaimctlGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSpacePermission = `-- name: RemoveSpacePermission :exec
DELETE FROM claimctl.space_permissions
WHERE space_id = $1 AND (
    (group_id = $2) OR
    (user_id = $3)
)
`

type RemoveSpacePermissionParams struct {
	SpaceID pgtype.UUID `json:"spaceId"`
	GroupID pgtype.UUID `json:"groupId"`
	UserID  pgtype.UUID `json:"userId"`
}

func (q *Queries) RemoveSpacePermission(ctx context.Context, arg RemoveSpacePermissionParams) error {
	_, err := q.db.Exec(ctx, removeSpacePermission, arg.SpaceID, arg.GroupID, arg.UserID)
	return err
}

const removeUserFromGroup = `-- name: RemoveUserFromGroup :exec
DELETE FROM claimctl.group_members
WHERE group_id = $1 AND user_id = $2
`

type RemoveUserFromGroupParams struct {
	GroupID uuid.UUID `json:"groupId"`
	UserID  uuid.UUID `json:"userId"`
}

func (q *Queries) RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error {
	_, err := q.db.Exec(ctx, removeUserFromGroup, arg.GroupID, arg.UserID)
	return err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE claimctl.groups
SET name = $2,
    description = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, description, created_at, updated_at
`

type UpdateGroupParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (ClaimctlGroup, error) {
	row := q.db.QueryRow(ctx, updateGroup, arg.ID, arg.Name, arg.Description)
	var i ClaimctlGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
