// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: health_checks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupOldHealthStatus = `-- name: CleanupOldHealthStatus :exec
DELETE FROM claimctl.resource_health_status
WHERE checked_at < $1
`

func (q *Queries) CleanupOldHealthStatus(ctx context.Context, checkedAt int64) error {
	_, err := q.db.Exec(ctx, cleanupOldHealthStatus, checkedAt)
	return err
}

const createHealthStatus = `-- name: CreateHealthStatus :one
INSERT INTO claimctl.resource_health_status (
    resource_id, status, response_time_ms, error_message, checked_at
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, resource_id, status, response_time_ms, error_message, checked_at, created_at
`

type CreateHealthStatusParams struct {
	ResourceID     uuid.UUID   `json:"resourceId"`
	Status         string      `json:"status"`
	ResponseTimeMs pgtype.Int4 `json:"responseTimeMs"`
	ErrorMessage   pgtype.Text `json:"errorMessage"`
	CheckedAt      int64       `json:"checkedAt"`
}

func (q *Queries) CreateHealthStatus(ctx context.Context, arg CreateHealthStatusParams) (ClaimctlResourceHealthStatus, error) {
	row := q.db.QueryRow(ctx, createHealthStatus,
		arg.ResourceID,
		arg.Status,
		arg.ResponseTimeMs,
		arg.ErrorMessage,
		arg.CheckedAt,
	)
	var i ClaimctlResourceHealthStatus
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.Status,
		&i.ResponseTimeMs,
		&i.ErrorMessage,
		&i.CheckedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHealthConfig = `-- name: DeleteHealthConfig :exec
DELETE FROM claimctl.resource_health_configs WHERE resource_id = $1
`

func (q *Queries) DeleteHealthConfig(ctx context.Context, resourceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteHealthConfig, resourceID)
	return err
}

const getAllEnabledHealthConfigs = `-- name: GetAllEnabledHealthConfigs :many
SELECT resource_id, enabled, check_type, target, interval_seconds, timeout_seconds, retry_count, created_at, updated_at FROM claimctl.resource_health_configs
WHERE enabled = true
`

func (q *Queries) GetAllEnabledHealthConfigs(ctx context.Context) ([]ClaimctlResourceHealthConfig, error) {
	rows, err := q.db.Query(ctx, getAllEnabledHealthConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimctlResourceHealthConfig
	for rows.Next() {
		var i ClaimctlResourceHealthConfig
		if err := rows.Scan(
			&i.ResourceID,
			&i.Enabled,
			&i.CheckType,
			&i.Target,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.RetryCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHealthConfig = `-- name: GetHealthConfig :one
SELECT resource_id, enabled, check_type, target, interval_seconds, timeout_seconds, retry_count, created_at, updated_at FROM claimctl.resource_health_configs WHERE resource_id = $1
`

func (q *Queries) GetHealthConfig(ctx context.Context, resourceID uuid.UUID) (ClaimctlResourceHealthConfig, error) {
	row := q.db.QueryRow(ctx, getHealthConfig, resourceID)
	var i ClaimctlResourceHealthConfig
	err := row.Scan(
		&i.ResourceID,
		&i.Enabled,
		&i.CheckType,
		&i.Target,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.RetryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHealthHistory = `-- name: GetHealthHistory :many
SELECT id, resource_id, status, response_time_ms, error_message, checked_at, created_at FROM claimctl.resource_health_status
WHERE resource_id = $1
ORDER BY checked_at DESC
LIMIT $2
`

type GetHealthHistoryParams struct {
	ResourceID uuid.UUID `json:"resourceId"`
	Limit      int32     `json:"limit"`
}

func (q *Queries) GetHealthHistory(ctx context.Context, arg GetHealthHistoryParams) ([]ClaimctlResourceHealthStatus, error) {
	rows, err := q.db.Query(ctx, getHealthHistory, arg.ResourceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimctlResourceHealthStatus
	for rows.Next() {
		var i ClaimctlResourceHealthStatus
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Status,
			&i.ResponseTimeMs,
			&i.ErrorMessage,
			&i.CheckedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHealthStatus = `-- name: GetHealthStatus :one
SELECT id, resource_id, status, response_time_ms, error_message, checked_at, created_at FROM claimctl.resource_health_status
WHERE resource_id = $1
ORDER BY checked_at DESC
LIMIT 1
`

func (q *Queries) GetHealthStatus(ctx context.Context, resourceID uuid.UUID) (ClaimctlResourceHealthStatus, error) {
	row := q.db.QueryRow(ctx, getHealthStatus, resourceID)
	var i ClaimctlResourceHealthStatus
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.Status,
		&i.ResponseTimeMs,
		&i.ErrorMessage,
		&i.CheckedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getResourcesDueForCheck = `-- name: GetResourcesDueForCheck :many
SELECT
    c.resource_id,
    c.interval_seconds,
    COALESCE(MAX(s.checked_at), 0) as last_checked_at
FROM claimctl.resource_health_configs c
LEFT JOIN claimctl.resource_health_status s ON c.resource_id = s.resource_id
WHERE c.enabled = true
GROUP BY c.resource_id, c.interval_seconds
HAVING COALESCE(MAX(s.checked_at), 0) + c.interval_seconds <= EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT
`

type GetResourcesDueForCheckRow struct {
	ResourceID      uuid.UUID   `json:"resourceId"`
	IntervalSeconds pgtype.Int4 `json:"intervalSeconds"`
	LastCheckedAt   interface{} `json:"lastCheckedAt"`
}

func (q *Queries) GetResourcesDueForCheck(ctx context.Context) ([]GetResourcesDueForCheckRow, error) {
	rows, err := q.db.Query(ctx, getResourcesDueForCheck)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResourcesDueForCheckRow
	for rows.Next() {
		var i GetResourcesDueForCheckRow
		if err := rows.Scan(&i.ResourceID, &i.IntervalSeconds, &i.LastCheckedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHealthConfig = `-- name: UpsertHealthConfig :one
INSERT INTO claimctl.resource_health_configs (
    resource_id, enabled, check_type, target, interval_seconds, timeout_seconds, retry_count
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (resource_id) DO UPDATE SET
    enabled = EXCLUDED.enabled,
    check_type = EXCLUDED.check_type,
    target = EXCLUDED.target,
    interval_seconds = EXCLUDED.interval_seconds,
    timeout_seconds = EXCLUDED.timeout_seconds,
    retry_count = EXCLUDED.retry_count,
    updated_at = EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT
RETURNING resource_id, enabled, check_type, target, interval_seconds, timeout_seconds, retry_count, created_at, updated_at
`

type UpsertHealthConfigParams struct {
	ResourceID      uuid.UUID   `json:"resourceId"`
	Enabled         pgtype.Bool `json:"enabled"`
	CheckType       string      `json:"checkType"`
	Target          string      `json:"target"`
	IntervalSeconds pgtype.Int4 `json:"intervalSeconds"`
	TimeoutSeconds  pgtype.Int4 `json:"timeoutSeconds"`
	RetryCount      pgtype.Int4 `json:"retryCount"`
}

func (q *Queries) UpsertHealthConfig(ctx context.Context, arg UpsertHealthConfigParams) (ClaimctlResourceHealthConfig, error) {
	row := q.db.QueryRow(ctx, upsertHealthConfig,
		arg.ResourceID,
		arg.Enabled,
		arg.CheckType,
		arg.Target,
		arg.IntervalSeconds,
		arg.TimeoutSeconds,
		arg.RetryCount,
	)
	var i ClaimctlResourceHealthConfig
	err := row.Scan(
		&i.ResourceID,
		&i.Enabled,
		&i.CheckType,
		&i.Target,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.RetryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
