// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	types "github.com/thetaqitahmid/claimctl/internal/types"
)

type AppSetting struct {
	Key         string             `json:"key"`
	Value       string             `json:"value"`
	Category    string             `json:"category"`
	Description pgtype.Text        `json:"description"`
	IsSecret    bool               `json:"isSecret"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type ClaimctlApiToken struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"userId"`
	Name       string             `json:"name"`
	TokenHash  string             `json:"tokenHash"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
	ExpiresAt  pgtype.Timestamptz `json:"expiresAt"`
	LastUsedAt pgtype.Timestamptz `json:"lastUsedAt"`
}

type ClaimctlAuditLog struct {
	ID         uuid.UUID   `json:"id"`
	ActorID    pgtype.UUID `json:"actorId"`
	Action     string      `json:"action"`
	EntityType string      `json:"entityType"`
	EntityID   pgtype.Text `json:"entityId"`
	Changes    []byte      `json:"changes"`
	IpAddress  pgtype.Text `json:"ipAddress"`
	CreatedAt  int64       `json:"createdAt"`
}

type ClaimctlGroup struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type ClaimctlGroupMember struct {
	GroupID  uuid.UUID          `json:"groupId"`
	UserID   uuid.UUID          `json:"userId"`
	JoinedAt pgtype.Timestamptz `json:"joinedAt"`
}

type ClaimctlMaintenanceAuditLog struct {
	ID            uuid.UUID   `json:"id"`
	ResourceID    uuid.UUID   `json:"resourceId"`
	PreviousState bool        `json:"previousState"`
	NewState      bool        `json:"newState"`
	ChangedBy     uuid.UUID   `json:"changedBy"`
	ChangedAt     pgtype.Int8 `json:"changedAt"`
	Reason        pgtype.Text `json:"reason"`
}

type ClaimctlReservation struct {
	ID               uuid.UUID          `json:"id"`
	ResourceID       uuid.UUID          `json:"resourceId"`
	UserID           uuid.UUID          `json:"userId"`
	Status           pgtype.Text        `json:"status"`
	QueuePosition    pgtype.Int4        `json:"queuePosition"`
	StartTime        pgtype.Int8        `json:"startTime"`
	EndTime          pgtype.Int8        `json:"endTime"`
	CreatedAt        pgtype.Int8        `json:"createdAt"`
	UpdatedAt        pgtype.Int8        `json:"updatedAt"`
	ScheduledEndTime pgtype.Timestamptz `json:"scheduledEndTime"`
	Duration         pgtype.Interval    `json:"duration"`
}

type ClaimctlReservationHistory struct {
	ID            uuid.UUID   `json:"id"`
	ResourceID    uuid.UUID   `json:"resourceId"`
	ReservationID pgtype.UUID `json:"reservationId"`
	Action        string      `json:"action"`
	UserID        uuid.UUID   `json:"userId"`
	Timestamp     pgtype.Int8 `json:"timestamp"`
	Details       types.JSONB `json:"details"`
}

type ClaimctlResource struct {
	ID                 uuid.UUID        `json:"id"`
	Name               string           `json:"name"`
	Type               string           `json:"type"`
	Labels             types.JSONBArray `json:"labels"`
	Properties         types.JSONBMap   `json:"properties"`
	SpaceID            uuid.UUID        `json:"spaceId"`
	CreatedAt          pgtype.Int8      `json:"createdAt"`
	UpdatedAt          pgtype.Int8      `json:"updatedAt"`
	IsUnderMaintenance pgtype.Bool      `json:"isUnderMaintenance"`
}

type ClaimctlResourceHealthConfig struct {
	ResourceID      uuid.UUID   `json:"resourceId"`
	Enabled         pgtype.Bool `json:"enabled"`
	CheckType       string      `json:"checkType"`
	Target          string      `json:"target"`
	IntervalSeconds pgtype.Int4 `json:"intervalSeconds"`
	TimeoutSeconds  pgtype.Int4 `json:"timeoutSeconds"`
	RetryCount      pgtype.Int4 `json:"retryCount"`
	CreatedAt       pgtype.Int8 `json:"createdAt"`
	UpdatedAt       pgtype.Int8 `json:"updatedAt"`
}

type ClaimctlResourceHealthStatus struct {
	ID             uuid.UUID   `json:"id"`
	ResourceID     uuid.UUID   `json:"resourceId"`
	Status         string      `json:"status"`
	ResponseTimeMs pgtype.Int4 `json:"responseTimeMs"`
	ErrorMessage   pgtype.Text `json:"errorMessage"`
	CheckedAt      int64       `json:"checkedAt"`
	CreatedAt      pgtype.Int8 `json:"createdAt"`
}

type ClaimctlResourceWebhook struct {
	ResourceID uuid.UUID `json:"resourceId"`
	WebhookID  uuid.UUID `json:"webhookId"`
	Events     []string  `json:"events"`
}

type ClaimctlSecret struct {
	ID          uuid.UUID   `json:"id"`
	Key         string      `json:"key"`
	Value       string      `json:"value"`
	Description pgtype.Text `json:"description"`
	CreatedAt   pgtype.Int8 `json:"createdAt"`
	UpdatedAt   pgtype.Int8 `json:"updatedAt"`
}

type ClaimctlSpace struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	CreatedAt   pgtype.Int8 `json:"createdAt"`
	UpdatedAt   pgtype.Int8 `json:"updatedAt"`
}

type ClaimctlSpacePermission struct {
	ID        uuid.UUID          `json:"id"`
	SpaceID   pgtype.UUID        `json:"spaceId"`
	GroupID   pgtype.UUID        `json:"groupId"`
	UserID    pgtype.UUID        `json:"userId"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type ClaimctlUser struct {
	ID                  uuid.UUID          `json:"id"`
	Email               string             `json:"email"`
	Name                string             `json:"name"`
	Password            string             `json:"password"`
	CreatedAt           pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt           pgtype.Timestamptz `json:"updatedAt"`
	Role                string             `json:"role"`
	Status              string             `json:"status"`
	LastLogin           pgtype.Timestamptz `json:"lastLogin"`
	FailedLoginAttempts int32              `json:"failedLoginAttempts"`
	LockedUntil         pgtype.Timestamptz `json:"lockedUntil"`
	SlackDestination    pgtype.Text        `json:"slackDestination"`
	TeamsWebhookUrl     pgtype.Text        `json:"teamsWebhookUrl"`
	NotificationEmail   pgtype.Text        `json:"notificationEmail"`
}

type ClaimctlUserNotificationPreference struct {
	UserID    uuid.UUID   `json:"userId"`
	EventType string      `json:"eventType"`
	Channel   string      `json:"channel"`
	Enabled   bool        `json:"enabled"`
	CreatedAt pgtype.Int8 `json:"createdAt"`
	UpdatedAt pgtype.Int8 `json:"updatedAt"`
}

type ClaimctlWebhook struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	Url           string      `json:"url"`
	Method        string      `json:"method"`
	Headers       []byte      `json:"headers"`
	Template      pgtype.Text `json:"template"`
	Description   pgtype.Text `json:"description"`
	SigningSecret string      `json:"signingSecret"`
	CreatedAt     pgtype.Int8 `json:"createdAt"`
	UpdatedAt     pgtype.Int8 `json:"updatedAt"`
}

type ClaimctlWebhookLog struct {
	ID           uuid.UUID        `json:"id"`
	WebhookID    uuid.UUID        `json:"webhookId"`
	Event        string           `json:"event"`
	StatusCode   int32            `json:"statusCode"`
	RequestBody  string           `json:"requestBody"`
	ResponseBody string           `json:"responseBody"`
	DurationMs   int32            `json:"durationMs"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
}
