// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: preferences.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getUserPreference = `-- name: GetUserPreference :one
SELECT user_id, event_type, channel, enabled, created_at, updated_at FROM claimctl.user_notification_preferences
WHERE user_id = $1 AND event_type = $2 AND channel = $3
`

type GetUserPreferenceParams struct {
	UserID    uuid.UUID `json:"userId"`
	EventType string    `json:"eventType"`
	Channel   string    `json:"channel"`
}

func (q *Queries) GetUserPreference(ctx context.Context, arg GetUserPreferenceParams) (ClaimctlUserNotificationPreference, error) {
	row := q.db.QueryRow(ctx, getUserPreference, arg.UserID, arg.EventType, arg.Channel)
	var i ClaimctlUserNotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.EventType,
		&i.Channel,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPreferences = `-- name: GetUserPreferences :many
SELECT user_id, event_type, channel, enabled, created_at, updated_at FROM claimctl.user_notification_preferences
WHERE user_id = $1
`

func (q *Queries) GetUserPreferences(ctx context.Context, userID uuid.UUID) ([]ClaimctlUserNotificationPreference, error) {
	rows, err := q.db.Query(ctx, getUserPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimctlUserNotificationPreference
	for rows.Next() {
		var i ClaimctlUserNotificationPreference
		if err := rows.Scan(
			&i.UserID,
			&i.EventType,
			&i.Channel,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPreference = `-- name: UpsertPreference :one
INSERT INTO claimctl.user_notification_preferences (user_id, event_type, channel, enabled)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, event_type, channel)
DO UPDATE SET enabled = EXCLUDED.enabled, updated_at = extract(epoch from now())
RETURNING user_id, event_type, channel, enabled, created_at, updated_at
`

type UpsertPreferenceParams struct {
	UserID    uuid.UUID `json:"userId"`
	EventType string    `json:"eventType"`
	Channel   string    `json:"channel"`
	Enabled   bool      `json:"enabled"`
}

func (q *Queries) UpsertPreference(ctx context.Context, arg UpsertPreferenceParams) (ClaimctlUserNotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertPreference,
		arg.UserID,
		arg.EventType,
		arg.Channel,
		arg.Enabled,
	)
	var i ClaimctlUserNotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.EventType,
		&i.Channel,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
