// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcquireResourceLock(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	ActivateReservation(ctx context.Context, arg ActivateReservationParams) error
	AddReservationHistoryLog(ctx context.Context, arg AddReservationHistoryLogParams) (ClaimctlReservationHistory, error)
	AddResourceWebhook(ctx context.Context, arg AddResourceWebhookParams) error
	AddSpacePermission(ctx context.Context, arg AddSpacePermissionParams) error
	AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error
	CancelAllReservationsForResource(ctx context.Context, arg CancelAllReservationsForResourceParams) error
	CancelReservation(ctx context.Context, arg CancelReservationParams) error
	CleanupOldHealthStatus(ctx context.Context, checkedAt int64) error
	CleanupOldWebhookLogs(ctx context.Context, createdAt pgtype.Timestamp) error
	CompleteReservation(ctx context.Context, arg CompleteReservationParams) error
	CountAdminUsers(ctx context.Context) (int64, error)
	CountPendingReservations(ctx context.Context, resourceID uuid.UUID) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ClaimctlApiToken, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (ClaimctlAuditLog, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (ClaimctlGroup, error)
	CreateHealthStatus(ctx context.Context, arg CreateHealthStatusParams) (ClaimctlResourceHealthStatus, error)
	CreateNewResource(ctx context.Context, arg CreateNewResourceParams) (ClaimctlResource, error)
	CreateReservation(ctx context.Context, arg CreateReservationParams) (ClaimctlReservation, error)
	CreateSecret(ctx context.Context, arg CreateSecretParams) (ClaimctlSecret, error)
	CreateSpace(ctx context.Context, arg CreateSpaceParams) (ClaimctlSpace, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (ClaimctlWebhook, error)
	CreateWebhookLog(ctx context.Context, arg CreateWebhookLogParams) (ClaimctlWebhookLog, error)
	DeleteGroup(ctx context.Context, id uuid.UUID) error
	DeleteHealthConfig(ctx context.Context, resourceID uuid.UUID) error
	DeleteResourceById(ctx context.Context, id uuid.UUID) error
	DeleteSecret(ctx context.Context, id uuid.UUID) error
	DeleteSpace(ctx context.Context, id uuid.UUID) error
	DeleteUserById(ctx context.Context, id uuid.UUID) error
	DeleteWebhook(ctx context.Context, id uuid.UUID) error
	ExpireReservation(ctx context.Context, arg ExpireReservationParams) error
	FindActiveReservationByResource(ctx context.Context, resourceID uuid.UUID) (ClaimctlReservation, error)
	FindAllReservations(ctx context.Context) ([]FindAllReservationsRow, error)
	FindAllResources(ctx context.Context) ([]ClaimctlResource, error)
	FindAllUsers(ctx context.Context) ([]ClaimctlUser, error)
	FindExpiredActiveReservations(ctx context.Context) ([]ClaimctlReservation, error)
	FindPendingReservationsByResource(ctx context.Context, resourceID uuid.UUID) ([]ClaimctlReservation, error)
	FindReservationById(ctx context.Context, id uuid.UUID) (ClaimctlReservation, error)
	FindReservationsByResource(ctx context.Context, resourceID uuid.UUID) ([]FindReservationsByResourceRow, error)
	FindReservationsByUser(ctx context.Context, userID uuid.UUID) ([]FindReservationsByUserRow, error)
	FindResourceById(ctx context.Context, id uuid.UUID) (ClaimctlResource, error)
	FindResourceByName(ctx context.Context, name string) (ClaimctlResource, error)
	FindUserActiveReservations(ctx context.Context, userID uuid.UUID) ([]FindUserActiveReservationsRow, error)
	FindUserByEmail(ctx context.Context, email string) (ClaimctlUser, error)
	FindUserById(ctx context.Context, id uuid.UUID) (ClaimctlUser, error)
	FindUserReservationForResource(ctx context.Context, arg FindUserReservationForResourceParams) (ClaimctlReservation, error)
	GetAPITokenByHash(ctx context.Context, tokenHash string) (ClaimctlApiToken, error)
	GetAllEnabledHealthConfigs(ctx context.Context) ([]ClaimctlResourceHealthConfig, error)
	GetAllResourcesWithReservationStatus(ctx context.Context) ([]GetAllResourcesWithReservationStatusRow, error)
	GetAllResourcesWithReservationStatusForUser(ctx context.Context, userID pgtype.UUID) ([]GetAllResourcesWithReservationStatusForUserRow, error)
	GetAuditLogs(ctx context.Context, arg GetAuditLogsParams) ([]GetAuditLogsRow, error)
	GetGroup(ctx context.Context, id uuid.UUID) (ClaimctlGroup, error)
	GetGroupByName(ctx context.Context, name string) (ClaimctlGroup, error)
	GetHealthConfig(ctx context.Context, resourceID uuid.UUID) (ClaimctlResourceHealthConfig, error)
	GetHealthHistory(ctx context.Context, arg GetHealthHistoryParams) ([]ClaimctlResourceHealthStatus, error)
	GetHealthStatus(ctx context.Context, resourceID uuid.UUID) (ClaimctlResourceHealthStatus, error)
	GetMaintenanceHistory(ctx context.Context, resourceID uuid.UUID) ([]GetMaintenanceHistoryRow, error)
	GetNextInQueue(ctx context.Context, resourceID uuid.UUID) (ClaimctlReservation, error)
	GetPasswordById(ctx context.Context, id uuid.UUID) (string, error)
	GetQueueForResource(ctx context.Context, resourceID uuid.UUID) ([]GetQueueForResourceRow, error)
	GetRecentHistoryByAction(ctx context.Context, arg GetRecentHistoryByActionParams) ([]GetRecentHistoryByActionRow, error)
	GetReservationHistory(ctx context.Context, reservationID pgtype.UUID) ([]GetReservationHistoryRow, error)
	GetResourceMaintenanceStatus(ctx context.Context, id uuid.UUID) (pgtype.Bool, error)
	GetResourceName(ctx context.Context, id uuid.UUID) (string, error)
	GetResourceReservationHistory(ctx context.Context, resourceID uuid.UUID) ([]GetResourceReservationHistoryRow, error)
	GetResourceReservationStatus(ctx context.Context, id uuid.UUID) (GetResourceReservationStatusRow, error)
	GetResourceStats(ctx context.Context, resourceID uuid.UUID) (GetResourceStatsRow, error)
	GetResourceTest(ctx context.Context, id uuid.UUID) (GetResourceTestRow, error)
	GetResourceWebhooks(ctx context.Context, resourceID uuid.UUID) ([]GetResourceWebhooksRow, error)
	GetResourcesDueForCheck(ctx context.Context) ([]GetResourcesDueForCheckRow, error)
	GetSecret(ctx context.Context, id uuid.UUID) (ClaimctlSecret, error)
	GetSecretByKey(ctx context.Context, key string) (ClaimctlSecret, error)
	GetSetting(ctx context.Context, key string) (AppSetting, error)
	GetSettings(ctx context.Context) ([]AppSetting, error)
	GetSpace(ctx context.Context, id uuid.UUID) (ClaimctlSpace, error)
	GetSpaceByName(ctx context.Context, name string) (ClaimctlSpace, error)
	GetSpacePermissions(ctx context.Context, spaceID pgtype.UUID) ([]GetSpacePermissionsRow, error)
	GetUserGroups(ctx context.Context, userID uuid.UUID) ([]ClaimctlGroup, error)
	GetUserPreference(ctx context.Context, arg GetUserPreferenceParams) (ClaimctlUserNotificationPreference, error)
	GetUserPreferences(ctx context.Context, userID uuid.UUID) ([]ClaimctlUserNotificationPreference, error)
	GetUserQueuePosition(ctx context.Context, arg GetUserQueuePositionParams) (pgtype.Int4, error)
	GetUserReservationHistory(ctx context.Context, userID uuid.UUID) ([]GetUserReservationHistoryRow, error)
	GetWebhook(ctx context.Context, id uuid.UUID) (ClaimctlWebhook, error)
	GetWebhookLogs(ctx context.Context, arg GetWebhookLogsParams) ([]ClaimctlWebhookLog, error)
	GetWebhooksForEvent(ctx context.Context, arg GetWebhooksForEventParams) ([]ClaimctlWebhook, error)
	HasSpacePermission(ctx context.Context, arg HasSpacePermissionParams) (bool, error)
	ListAPITokens(ctx context.Context, userID uuid.UUID) ([]ClaimctlApiToken, error)
	ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]ListGroupMembersRow, error)
	ListGroups(ctx context.Context) ([]ClaimctlGroup, error)
	ListSecrets(ctx context.Context) ([]ClaimctlSecret, error)
	ListSpaces(ctx context.Context) ([]ClaimctlSpace, error)
	ListSpacesForUser(ctx context.Context, userID pgtype.UUID) ([]ClaimctlSpace, error)
	ListWebhooks(ctx context.Context) ([]ClaimctlWebhook, error)
	LogMaintenanceChange(ctx context.Context, arg LogMaintenanceChangeParams) (ClaimctlMaintenanceAuditLog, error)
	PromoteNextInQueue(ctx context.Context, arg PromoteNextInQueueParams) error
	RemoveResourceWebhook(ctx context.Context, arg RemoveResourceWebhookParams) error
	RemoveSpacePermission(ctx context.Context, arg RemoveSpacePermissionParams) error
	RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) error
	ResetUserFailedLoginAttempts(ctx context.Context, id uuid.UUID) error
	RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) error
	SetResourceMaintenanceMode(ctx context.Context, arg SetResourceMaintenanceModeParams) (ClaimctlResource, error)
	UpdateAPITokenLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (ClaimctlGroup, error)
	UpdateQueuePositions(ctx context.Context, arg UpdateQueuePositionsParams) error
	UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) error
	UpdateResourceById(ctx context.Context, arg UpdateResourceByIdParams) error
	UpdateSecret(ctx context.Context, arg UpdateSecretParams) (ClaimctlSecret, error)
	UpdateSpace(ctx context.Context, arg UpdateSpaceParams) (ClaimctlSpace, error)
	UpdateUserById(ctx context.Context, arg UpdateUserByIdParams) error
	UpdateUserChannelConfig(ctx context.Context, arg UpdateUserChannelConfigParams) (ClaimctlUser, error)
	UpdateUserFailedLoginAttempts(ctx context.Context, arg UpdateUserFailedLoginAttemptsParams) (int32, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (ClaimctlWebhook, error)
	UpsertHealthConfig(ctx context.Context, arg UpsertHealthConfigParams) (ClaimctlResourceHealthConfig, error)
	UpsertPreference(ctx context.Context, arg UpsertPreferenceParams) (ClaimctlUserNotificationPreference, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) (AppSetting, error)
	VerifyResourceNameIsUnique(ctx context.Context, name string) (int64, error)
	VerifyUserEmailIsUnique(ctx context.Context, email string) (int64, error)
}

var _ Querier = (*Queries)(nil)
