// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: reservation_history.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	types "github.com/thetaqitahmid/claimctl/internal/types"
)

const addReservationHistoryLog = `-- name: AddReservationHistoryLog :one
INSERT INTO claimctl.reservation_history (resource_id, reservation_id, action, user_id, details)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, resource_id, reservation_id, action, user_id, timestamp, details
`

type AddReservationHistoryLogParams struct {
	ResourceID    uuid.UUID   `json:"resourceId"`
	ReservationID pgtype.UUID `json:"reservationId"`
	Action        string      `json:"action"`
	UserID        uuid.UUID   `json:"userId"`
	Details       types.JSONB `json:"details"`
}

func (q *Queries) AddReservationHistoryLog(ctx context.Context, arg AddReservationHistoryLogParams) (ClaimctlReservationHistory, error) {
	row := q.db.QueryRow(ctx, addReservationHistoryLog,
		arg.ResourceID,
		arg.ReservationID,
		arg.Action,
		arg.UserID,
		arg.Details,
	)
	var i ClaimctlReservationHistory
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.ReservationID,
		&i.Action,
		&i.UserID,
		&i.Timestamp,
		&i.Details,
	)
	return i, err
}

const getRecentHistoryByAction = `-- name: GetRecentHistoryByAction :many
SELECT
    rh.id,
    rh.resource_id,
    r.name as resource_name,
    rh.reservation_id,
    rh.action,
    rh.user_id,
    u.name as user_name,
    rh.timestamp,
    rh.details
FROM claimctl.reservation_history rh
JOIN claimctl.resources r ON rh.resource_id = r.id
JOIN claimctl.users u ON rh.user_id = u.id
WHERE rh.action = $1
ORDER BY rh.timestamp DESC
LIMIT $2
`

type GetRecentHistoryByActionParams struct {
	Action string `json:"action"`
	Limit  int32  `json:"limit"`
}

type GetRecentHistoryByActionRow struct {
	ID            uuid.UUID   `json:"id"`
	ResourceID    uuid.UUID   `json:"resourceId"`
	ResourceName  string      `json:"resourceName"`
	ReservationID pgtype.UUID `json:"reservationId"`
	Action        string      `json:"action"`
	UserID        uuid.UUID   `json:"userId"`
	UserName      string      `json:"userName"`
	Timestamp     pgtype.Int8 `json:"timestamp"`
	Details       types.JSONB `json:"details"`
}

func (q *Queries) GetRecentHistoryByAction(ctx context.Context, arg GetRecentHistoryByActionParams) ([]GetRecentHistoryByActionRow, error) {
	rows, err := q.db.Query(ctx, getRecentHistoryByAction, arg.Action, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentHistoryByActionRow
	for rows.Next() {
		var i GetRecentHistoryByActionRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.ResourceName,
			&i.ReservationID,
			&i.Action,
			&i.UserID,
			&i.UserName,
			&i.Timestamp,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReservationHistory = `-- name: GetReservationHistory :many
SELECT
    rh.id,
    rh.action,
    rh.user_id,
    u.name as user_name,
    rh.timestamp,
    rh.details
FROM claimctl.reservation_history rh
JOIN claimctl.users u ON rh.user_id = u.id
WHERE rh.reservation_id = $1
ORDER BY rh.timestamp DESC
`

type GetReservationHistoryRow struct {
	ID        uuid.UUID   `json:"id"`
	Action    string      `json:"action"`
	UserID    uuid.UUID   `json:"userId"`
	UserName  string      `json:"userName"`
	Timestamp pgtype.Int8 `json:"timestamp"`
	Details   types.JSONB `json:"details"`
}

func (q *Queries) GetReservationHistory(ctx context.Context, reservationID pgtype.UUID) ([]GetReservationHistoryRow, error) {
	rows, err := q.db.Query(ctx, getReservationHistory, reservationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReservationHistoryRow
	for rows.Next() {
		var i GetReservationHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.UserID,
			&i.UserName,
			&i.Timestamp,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourceReservationHistory = `-- name: GetResourceReservationHistory :many
SELECT
    rh.id,
    rh.resource_id,
    rh.reservation_id,
    rh.action,
    rh.user_id,
    u.name as user_name,
    rh.timestamp,
    rh.details,
    r.name as resource_name
FROM claimctl.reservation_history rh
JOIN claimctl.users u ON rh.user_id = u.id
JOIN claimctl.resources r ON rh.resource_id = r.id
WHERE rh.resource_id = $1
ORDER BY rh.timestamp DESC
`

type GetResourceReservationHistoryRow struct {
	ID            uuid.UUID   `json:"id"`
	ResourceID    uuid.UUID   `json:"resourceId"`
	ReservationID pgtype.UUID `json:"reservationId"`
	Action        string      `json:"action"`
	UserID        uuid.UUID   `json:"userId"`
	UserName      string      `json:"userName"`
	Timestamp     pgtype.Int8 `json:"timestamp"`
	Details       types.JSONB `json:"details"`
	ResourceName  string      `json:"resourceName"`
}

func (q *Queries) GetResourceReservationHistory(ctx context.Context, resourceID uuid.UUID) ([]GetResourceReservationHistoryRow, error) {
	rows, err := q.db.Query(ctx, getResourceReservationHistory, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResourceReservationHistoryRow
	for rows.Next() {
		var i GetResourceReservationHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.ReservationID,
			&i.Action,
			&i.UserID,
			&i.UserName,
			&i.Timestamp,
			&i.Details,
			&i.ResourceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourceStats = `-- name: GetResourceStats :one
SELECT
    COUNT(*) as total_reservations,
    COUNT(CASE WHEN rh.action = 'completed' THEN 1 END) as completed_reservations,
    COUNT(CASE WHEN rh.action = 'cancelled' THEN 1 END) as cancelled_reservations,
    COUNT(CASE WHEN rh.action = 'activated' THEN 1 END) as activated_reservations
FROM claimctl.reservation_history rh
WHERE rh.resource_id = $1
`

type GetResourceStatsRow struct {
	TotalReservations     int64 `json:"totalReservations"`
	CompletedReservations int64 `json:"completedReservations"`
	CancelledReservations int64 `json:"cancelledReservations"`
	ActivatedReservations int64 `json:"activatedReservations"`
}

func (q *Queries) GetResourceStats(ctx context.Context, resourceID uuid.UUID) (GetResourceStatsRow, error) {
	row := q.db.QueryRow(ctx, getResourceStats, resourceID)
	var i GetResourceStatsRow
	err := row.Scan(
		&i.TotalReservations,
		&i.CompletedReservations,
		&i.CancelledReservations,
		&i.ActivatedReservations,
	)
	return i, err
}

const getUserReservationHistory = `-- name: GetUserReservationHistory :many
SELECT
    rh.id,
    rh.resource_id,
    r.name as resource_name,
    rh.reservation_id,
    rh.action,
    rh.timestamp,
    rh.details
FROM claimctl.reservation_history rh
JOIN claimctl.resources r ON rh.resource_id = r.id
WHERE rh.user_id = $1
ORDER BY rh.timestamp DESC
`

type GetUserReservationHistoryRow struct {
	ID            uuid.UUID   `json:"id"`
	ResourceID    uuid.UUID   `json:"resourceId"`
	ResourceName  string      `json:"resourceName"`
	ReservationID pgtype.UUID `json:"reservationId"`
	Action        string      `json:"action"`
	Timestamp     pgtype.Int8 `json:"timestamp"`
	Details       types.JSONB `json:"details"`
}

func (q *Queries) GetUserReservationHistory(ctx context.Context, userID uuid.UUID) ([]GetUserReservationHistoryRow, error) {
	rows, err := q.db.Query(ctx, getUserReservationHistory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserReservationHistoryRow
	for rows.Next() {
		var i GetUserReservationHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.ResourceName,
			&i.ReservationID,
			&i.Action,
			&i.Timestamp,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
