// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: reservations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateReservation = `-- name: ActivateReservation :exec
UPDATE claimctl.reservations
SET
    status='active',
    start_time=$2,
    scheduled_end_time = CASE WHEN duration IS NOT NULL THEN (to_timestamp($3) + duration) ELSE NULL END,
    queue_position=0,
    updated_at=$4
WHERE id=$1 AND status='pending'
`

type ActivateReservationParams struct {
	ID          uuid.UUID   `json:"id"`
	StartTime   pgtype.Int8 `json:"startTime"`
	ToTimestamp float64     `json:"toTimestamp"`
	UpdatedAt   pgtype.Int8 `json:"updatedAt"`
}

func (q *Queries) ActivateReservation(ctx context.Context, arg ActivateReservationParams) error {
	_, err := q.db.Exec(ctx, activateReservation,
		arg.ID,
		arg.StartTime,
		arg.ToTimestamp,
		arg.UpdatedAt,
	)
	return err
}

const cancelAllReservationsForResource = `-- name: CancelAllReservationsForResource :exec
UPDATE claimctl.reservations
SET status='cancelled', end_time=$2, queue_position=NULL, updated_at=$2
WHERE resource_id=$1 AND status IN ('pending', 'active')
`

type CancelAllReservationsForResourceParams struct {
	ResourceID uuid.UUID   `json:"resourceId"`
	EndTime    pgtype.Int8 `json:"endTime"`
}

func (q *Queries) CancelAllReservationsForResource(ctx context.Context, arg CancelAllReservationsForResourceParams) error {
	_, err := q.db.Exec(ctx, cancelAllReservationsForResource, arg.ResourceID, arg.EndTime)
	return err
}

const cancelReservation = `-- name: CancelReservation :exec
UPDATE claimctl.reservations
SET status='cancelled', end_time=$2, queue_position=NULL, updated_at=$3
WHERE id=$1 AND status IN ('pending', 'active')
`

type CancelReservationParams struct {
	ID        uuid.UUID   `json:"id"`
	EndTime   pgtype.Int8 `json:"endTime"`
	UpdatedAt pgtype.Int8 `json:"updatedAt"`
}

func (q *Queries) CancelReservation(ctx context.Context, arg CancelReservationParams) error {
	_, err := q.db.Exec(ctx, cancelReservation, arg.ID, arg.EndTime, arg.UpdatedAt)
	return err
}

const completeReservation = `-- name: CompleteReservation :exec
UPDATE claimctl.reservations
SET status='completed', end_time=$2, updated_at=$3
WHERE id=$1 AND status='active'
`

type CompleteReservationParams struct {
	ID        uuid.UUID   `json:"id"`
	EndTime   pgtype.Int8 `json:"endTime"`
	UpdatedAt pgtype.Int8 `json:"updatedAt"`
}

func (q *Queries) CompleteReservation(ctx context.Context, arg CompleteReservationParams) error {
	_, err := q.db.Exec(ctx, completeReservation, arg.ID, arg.EndTime, arg.UpdatedAt)
	return err
}

const countPendingReservations = `-- name: CountPendingReservations :one
SELECT COUNT(*) as count
FROM claimctl.reservations
WHERE resource_id=$1 AND status='pending'
`

func (q *Queries) CountPendingReservations(ctx context.Context, resourceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingReservations, resourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReservation = `-- name: CreateReservation :one
INSERT INTO claimctl.reservations (resource_id, user_id, status, queue_position, start_time, duration, scheduled_end_time, updated_at)
VALUES ($1, $2,
    CASE
        WHEN (
            SELECT COUNT(*) FROM claimctl.reservations
            WHERE resource_id = $1 AND status IN ('pending', 'active')
        ) = 0 THEN 'active'
        ELSE 'pending'
    END,
    CASE
        WHEN (
            SELECT COUNT(*) FROM claimctl.reservations
            WHERE resource_id = $1 AND status IN ('pending', 'active')
        ) = 0 THEN 0
        ELSE COALESCE((
            SELECT MAX(queue_position) FROM claimctl.reservations
            WHERE resource_id = $1 AND status = 'pending'
        ), 0) + 1
    END,
    CASE
        WHEN (
            SELECT COUNT(*) FROM claimctl.reservations
            WHERE resource_id = $1 AND status IN ('pending', 'active')
        ) = 0 THEN EXTRACT(EPOCH FROM NOW())::BIGINT
        ELSE NULL
    END,
    $3,
    CASE
        WHEN (
            SELECT COUNT(*) FROM claimctl.reservations
            WHERE resource_id = $1 AND status IN ('pending', 'active')
        ) = 0 AND $3::INTERVAL IS NOT NULL THEN NOW() + $3::INTERVAL
        ELSE NULL
    END,
    EXTRACT(EPOCH FROM NOW())::BIGINT
)
RETURNING id, resource_id, user_id, status, queue_position, start_time, end_time, created_at, updated_at, scheduled_end_time, duration
`

type CreateReservationParams struct {
	ResourceID uuid.UUID       `json:"resourceId"`
	UserID     uuid.UUID       `json:"userId"`
	Duration   pgtype.Interval `json:"duration"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (ClaimctlReservation, error) {
	row := q.db.QueryRow(ctx, createReservation, arg.ResourceID, arg.UserID, arg.Duration)
	var i ClaimctlReservation
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.UserID,
		&i.Status,
		&i.QueuePosition,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScheduledEndTime,
		&i.Duration,
	)
	return i, err
}

const expireReservation = `-- name: ExpireReservation :exec
UPDATE claimctl.reservations
SET status='completed', end_time=EXTRACT(EPOCH FROM NOW())::BIGINT, updated_at=$2
WHERE id=$1
`

type ExpireReservationParams struct {
	ID        uuid.UUID   `json:"id"`
	UpdatedAt pgtype.Int8 `json:"updatedAt"`
}

func (q *Queries) ExpireReservation(ctx context.Context, arg ExpireReservationParams) error {
	_, err := q.db.Exec(ctx, expireReservation, arg.ID, arg.UpdatedAt)
	return err
}

const findActiveReservationByResource = `-- name: FindActiveReservationByResource :one
SELECT id, resource_id, user_id, status, queue_position, start_time, end_time, created_at, updated_at, scheduled_end_time, duration FROM claimctl.reservations
WHERE resource_id=$1 AND status='active'
`

func (q *Queries) FindActiveReservationByResource(ctx context.Context, resourceID uuid.UUID) (ClaimctlReservation, error) {
	row := q.db.QueryRow(ctx, findActiveReservationByResource, resourceID)
	var i ClaimctlReservation
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.UserID,
		&i.Status,
		&i.QueuePosition,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScheduledEndTime,
		&i.Duration,
	)
	return i, err
}

const findAllReservations = `-- name: FindAllReservations :many
SELECT r.id, r.resource_id, r.user_id, r.status, r.queue_position, r.start_time, r.end_time, r.created_at, r.updated_at, r.scheduled_end_time, r.duration, u.name as user_name, res.name as resource_name
FROM claimctl.reservations r
JOIN claimctl.users u ON r.user_id = u.id
JOIN claimctl.resources res ON r.resource_id = res.id
ORDER BY r.created_at DESC
`

type FindAllReservationsRow struct {
	ID               uuid.UUID          `json:"id"`
	ResourceID       uuid.UUID          `json:"resourceId"`
	UserID           uuid.UUID          `json:"userId"`
	Status           pgtype.Text        `json:"status"`
	QueuePosition    pgtype.Int4        `json:"queuePosition"`
	StartTime        pgtype.Int8        `json:"startTime"`
	EndTime          pgtype.Int8        `json:"endTime"`
	CreatedAt        pgtype.Int8        `json:"createdAt"`
	UpdatedAt        pgtype.Int8        `json:"updatedAt"`
	ScheduledEndTime pgtype.Timestamptz `json:"scheduledEndTime"`
	Duration         pgtype.Interval    `json:"duration"`
	UserName         string             `json:"userName"`
	ResourceName     string             `json:"resourceName"`
}

func (q *Queries) FindAllReservations(ctx context.Context) ([]FindAllReservationsRow, error) {
	rows, err := q.db.Query(ctx, findAllReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAllReservationsRow
	for rows.Next() {
		var i FindAllReservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.UserID,
			&i.Status,
			&i.QueuePosition,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ScheduledEndTime,
			&i.Duration,
			&i.UserName,
			&i.ResourceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findExpiredActiveReservations = `-- name: FindExpiredActiveReservations :many
SELECT id, resource_id, user_id, status, queue_position, start_time, end_time, created_at, updated_at, scheduled_end_time, duration FROM claimctl.reservations
WHERE status='active' AND scheduled_end_time IS NOT NULL AND scheduled_end_time < NOW()
`

func (q *Queries) FindExpiredActiveReservations(ctx context.Context) ([]ClaimctlReservation, error) {
	rows, err := q.db.Query(ctx, findExpiredActiveReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimctlReservation
	for rows.Next() {
		var i ClaimctlReservation
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.UserID,
			&i.Status,
			&i.QueuePosition,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ScheduledEndTime,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPendingReservationsByResource = `-- name: FindPendingReservationsByResource :many
SELECT id, resource_id, user_id, status, queue_position, start_time, end_time, created_at, updated_at, scheduled_end_time, duration FROM claimctl.reservations
WHERE resource_id=$1 AND status='pending'
ORDER BY queue_position
`

func (q *Queries) FindPendingReservationsByResource(ctx context.Context, resourceID uuid.UUID) ([]ClaimctlReservation, error) {
	rows, err := q.db.Query(ctx, findPendingReservationsByResource, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimctlReservation
	for rows.Next() {
		var i ClaimctlReservation
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.UserID,
			&i.Status,
			&i.QueuePosition,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ScheduledEndTime,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findReservationById = `-- name: FindReservationById :one
SELECT id, resource_id, user_id, status, queue_position, start_time, end_time, created_at, updated_at, scheduled_end_time, duration FROM claimctl.reservations WHERE id=$1
`

func (q *Queries) FindReservationById(ctx context.Context, id uuid.UUID) (ClaimctlReservation, error) {
	row := q.db.QueryRow(ctx, findReservationById, id)
	var i ClaimctlReservation
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.UserID,
		&i.Status,
		&i.QueuePosition,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScheduledEndTime,
		&i.Duration,
	)
	return i, err
}

const findReservationsByResource = `-- name: FindReservationsByResource :many
SELECT r.id, r.resource_id, r.user_id, r.status, r.queue_position, r.start_time, r.end_time, r.created_at, r.updated_at, r.scheduled_end_time, r.duration, u.name as user_name
FROM claimctl.reservations r
JOIN claimctl.users u ON r.user_id = u.id
WHERE r.resource_id=$1
ORDER BY r.created_at DESC
`

type FindReservationsByResourceRow struct {
	ID               uuid.UUID          `json:"id"`
	ResourceID       uuid.UUID          `json:"resourceId"`
	UserID           uuid.UUID          `json:"userId"`
	Status           pgtype.Text        `json:"status"`
	QueuePosition    pgtype.Int4        `json:"queuePosition"`
	StartTime        pgtype.Int8        `json:"startTime"`
	EndTime          pgtype.Int8        `json:"endTime"`
	CreatedAt        pgtype.Int8        `json:"createdAt"`
	UpdatedAt        pgtype.Int8        `json:"updatedAt"`
	ScheduledEndTime pgtype.Timestamptz `json:"scheduledEndTime"`
	Duration         pgtype.Interval    `json:"duration"`
	UserName         string             `json:"userName"`
}

func (q *Queries) FindReservationsByResource(ctx context.Context, resourceID uuid.UUID) ([]FindReservationsByResourceRow, error) {
	rows, err := q.db.Query(ctx, findReservationsByResource, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindReservationsByResourceRow
	for rows.Next() {
		var i FindReservationsByResourceRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.UserID,
			&i.Status,
			&i.QueuePosition,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ScheduledEndTime,
			&i.Duration,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findReservationsByUser = `-- name: FindReservationsByUser :many
SELECT r.id, r.resource_id, r.user_id, r.status, r.queue_position, r.start_time, r.end_time, r.created_at, r.updated_at, r.scheduled_end_time, r.duration, res.name as resource_name, res.type as resource_type
FROM claimctl.reservations r
JOIN claimctl.resources res ON r.resource_id = res.id
WHERE r.user_id=$1
ORDER BY r.created_at DESC
`

type FindReservationsByUserRow struct {
	ID               uuid.UUID          `json:"id"`
	ResourceID       uuid.UUID          `json:"resourceId"`
	UserID           uuid.UUID          `json:"userId"`
	Status           pgtype.Text        `json:"status"`
	QueuePosition    pgtype.Int4        `json:"queuePosition"`
	StartTime        pgtype.Int8        `json:"startTime"`
	EndTime          pgtype.Int8        `json:"endTime"`
	CreatedAt        pgtype.Int8        `json:"createdAt"`
	UpdatedAt        pgtype.Int8        `json:"updatedAt"`
	ScheduledEndTime pgtype.Timestamptz `json:"scheduledEndTime"`
	Duration         pgtype.Interval    `json:"duration"`
	ResourceName     string             `json:"resourceName"`
	ResourceType     string             `json:"resourceType"`
}

func (q *Queries) FindReservationsByUser(ctx context.Context, userID uuid.UUID) ([]FindReservationsByUserRow, error) {
	rows, err := q.db.Query(ctx, findReservationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindReservationsByUserRow
	for rows.Next() {
		var i FindReservationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.UserID,
			&i.Status,
			&i.QueuePosition,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ScheduledEndTime,
			&i.Duration,
			&i.ResourceName,
			&i.ResourceType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserActiveReservations = `-- name: FindUserActiveReservations :many
SELECT r.id, r.resource_id, r.user_id, r.status, r.queue_position, r.start_time, r.end_time, r.created_at, r.updated_at, r.scheduled_end_time, r.duration, res.name as resource_name, res.type as resource_type
FROM claimctl.reservations r
JOIN claimctl.resources res ON r.resource_id = res.id
WHERE r.user_id=$1 AND r.status IN ('pending', 'active')
ORDER BY r.created_at
`

type FindUserActiveReservationsRow struct {
	ID               uuid.UUID          `json:"id"`
	ResourceID       uuid.UUID          `json:"resourceId"`
	UserID           uuid.UUID          `json:"userId"`
	Status           pgtype.Text        `json:"status"`
	QueuePosition    pgtype.Int4        `json:"queuePosition"`
	StartTime        pgtype.Int8        `json:"startTime"`
	EndTime          pgtype.Int8        `json:"endTime"`
	CreatedAt        pgtype.Int8        `json:"createdAt"`
	UpdatedAt        pgtype.Int8        `json:"updatedAt"`
	ScheduledEndTime pgtype.Timestamptz `json:"scheduledEndTime"`
	Duration         pgtype.Interval    `json:"duration"`
	ResourceName     string             `json:"resourceName"`
	ResourceType     string             `json:"resourceType"`
}

func (q *Queries) FindUserActiveReservations(ctx context.Context, userID uuid.UUID) ([]FindUserActiveReservationsRow, error) {
	rows, err := q.db.Query(ctx, findUserActiveReservations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindUserActiveReservationsRow
	for rows.Next() {
		var i FindUserActiveReservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.UserID,
			&i.Status,
			&i.QueuePosition,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ScheduledEndTime,
			&i.Duration,
			&i.ResourceName,
			&i.ResourceType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserReservationForResource = `-- name: FindUserReservationForResource :one
SELECT id, resource_id, user_id, status, queue_position, start_time, end_time, created_at, updated_at, scheduled_end_time, duration FROM claimctl.reservations
WHERE user_id=$1 AND resource_id=$2 AND status IN ('pending', 'active')
ORDER BY
    CASE status
        WHEN 'active' THEN 1
        WHEN 'pending' THEN 2
    END,
    queue_position
LIMIT 1
`

type FindUserReservationForResourceParams struct {
	UserID     uuid.UUID `json:"userId"`
	ResourceID uuid.UUID `json:"resourceId"`
}

func (q *Queries) FindUserReservationForResource(ctx context.Context, arg FindUserReservationForResourceParams) (ClaimctlReservation, error) {
	row := q.db.QueryRow(ctx, findUserReservationForResource, arg.UserID, arg.ResourceID)
	var i ClaimctlReservation
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.UserID,
		&i.Status,
		&i.QueuePosition,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScheduledEndTime,
		&i.Duration,
	)
	return i, err
}

const getNextInQueue = `-- name: GetNextInQueue :one
SELECT id, resource_id, user_id, status, queue_position, start_time, end_time, created_at, updated_at, scheduled_end_time, duration FROM claimctl.reservations
WHERE resource_id=$1 AND status='pending'
ORDER BY queue_position
LIMIT 1
`

func (q *Queries) GetNextInQueue(ctx context.Context, resourceID uuid.UUID) (ClaimctlReservation, error) {
	row := q.db.QueryRow(ctx, getNextInQueue, resourceID)
	var i ClaimctlReservation
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.UserID,
		&i.Status,
		&i.QueuePosition,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScheduledEndTime,
		&i.Duration,
	)
	return i, err
}

const getQueueForResource = `-- name: GetQueueForResource :many
SELECT r.id, r.user_id, r.status, r.queue_position, r.start_time, r.end_time, r.scheduled_end_time, r.created_at, r.duration, u.name as user_name, u.email as user_email
FROM claimctl.reservations r
JOIN claimctl.users u ON r.user_id = u.id
WHERE r.resource_id=$1 AND r.status IN ('active', 'pending')
ORDER BY
    CASE r.status
        WHEN 'active' THEN 1
        WHEN 'pending' THEN 2
    END,
    r.queue_position
`

type GetQueueForResourceRow struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"userId"`
	Status           pgtype.Text        `json:"status"`
	QueuePosition    pgtype.Int4        `json:"queuePosition"`
	StartTime        pgtype.Int8        `json:"startTime"`
	EndTime          pgtype.Int8        `json:"endTime"`
	ScheduledEndTime pgtype.Timestamptz `json:"scheduledEndTime"`
	CreatedAt        pgtype.Int8        `json:"createdAt"`
	Duration         pgtype.Interval    `json:"duration"`
	UserName         string             `json:"userName"`
	UserEmail        string             `json:"userEmail"`
}

func (q *Queries) GetQueueForResource(ctx context.Context, resourceID uuid.UUID) ([]GetQueueForResourceRow, error) {
	rows, err := q.db.Query(ctx, getQueueForResource, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQueueForResourceRow
	for rows.Next() {
		var i GetQueueForResourceRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.QueuePosition,
			&i.StartTime,
			&i.EndTime,
			&i.ScheduledEndTime,
			&i.CreatedAt,
			&i.Duration,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserQueuePosition = `-- name: GetUserQueuePosition :one
SELECT queue_position
FROM claimctl.reservations
WHERE user_id=$1 AND resource_id=$2 AND status='pending'
`

type GetUserQueuePositionParams struct {
	UserID     uuid.UUID `json:"userId"`
	ResourceID uuid.UUID `json:"resourceId"`
}

func (q *Queries) GetUserQueuePosition(ctx context.Context, arg GetUserQueuePositionParams) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getUserQueuePosition, arg.UserID, arg.ResourceID)
	var queue_position pgtype.Int4
	err := row.Scan(&queue_position)
	return queue_position, err
}

const promoteNextInQueue = `-- name: PromoteNextInQueue :exec
UPDATE claimctl.reservations r
SET queue_position = queue_position - 1, updated_at = $2
WHERE r.resource_id=$1 AND r.status='pending' AND r.queue_position > 1
`

type PromoteNextInQueueParams struct {
	ResourceID uuid.UUID   `json:"resourceId"`
	UpdatedAt  pgtype.Int8 `json:"updatedAt"`
}

func (q *Queries) PromoteNextInQueue(ctx context.Context, arg PromoteNextInQueueParams) error {
	_, err := q.db.Exec(ctx, promoteNextInQueue, arg.ResourceID, arg.UpdatedAt)
	return err
}

const updateQueuePositions = `-- name: UpdateQueuePositions :exec
UPDATE claimctl.reservations r
SET queue_position = queue_position - 1, updated_at = $2
WHERE r.resource_id=$1 AND r.status='pending' AND r.queue_position > $3
`

type UpdateQueuePositionsParams struct {
	ResourceID    uuid.UUID   `json:"resourceId"`
	UpdatedAt     pgtype.Int8 `json:"updatedAt"`
	QueuePosition pgtype.Int4 `json:"queuePosition"`
}

func (q *Queries) UpdateQueuePositions(ctx context.Context, arg UpdateQueuePositionsParams) error {
	_, err := q.db.Exec(ctx, updateQueuePositions, arg.ResourceID, arg.UpdatedAt, arg.QueuePosition)
	return err
}

const updateReservationStatus = `-- name: UpdateReservationStatus :exec
UPDATE claimctl.reservations
SET status=$2, updated_at=$3
WHERE id=$1
`

type UpdateReservationStatusParams struct {
	ID        uuid.UUID   `json:"id"`
	Status    pgtype.Text `json:"status"`
	UpdatedAt pgtype.Int8 `json:"updatedAt"`
}

func (q *Queries) UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) error {
	_, err := q.db.Exec(ctx, updateReservationStatus, arg.ID, arg.Status, arg.UpdatedAt)
	return err
}
