// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: resources.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	types "github.com/thetaqitahmid/claimctl/internal/types"
)

const acquireResourceLock = `-- name: AcquireResourceLock :one
SELECT id FROM claimctl.resources WHERE id=$1 FOR UPDATE
`

func (q *Queries) AcquireResourceLock(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, acquireResourceLock, id)
	err := row.Scan(&id)
	return id, err
}

const createNewResource = `-- name: CreateNewResource :one
INSERT INTO claimctl.resources (name, labels, type, space_id, properties)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, type, labels, properties, space_id, created_at, updated_at, is_under_maintenance
`

type CreateNewResourceParams struct {
	Name       string           `json:"name"`
	Labels     types.JSONBArray `json:"labels"`
	Type       string           `json:"type"`
	SpaceID    uuid.UUID        `json:"spaceId"`
	Properties types.JSONBMap   `json:"properties"`
}

func (q *Queries) CreateNewResource(ctx context.Context, arg CreateNewResourceParams) (ClaimctlResource, error) {
	row := q.db.QueryRow(ctx, createNewResource,
		arg.Name,
		arg.Labels,
		arg.Type,
		arg.SpaceID,
		arg.Properties,
	)
	var i ClaimctlResource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Labels,
		&i.Properties,
		&i.SpaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsUnderMaintenance,
	)
	return i, err
}

const deleteResourceById = `-- name: DeleteResourceById :exec
DELETE FROM claimctl.resources WHERE id=$1
`

func (q *Queries) DeleteResourceById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteResourceById, id)
	return err
}

const findAllResources = `-- name: FindAllResources :many
SELECT id, name, type, labels, properties, space_id, created_at, updated_at, is_under_maintenance FROM claimctl.resources
`

func (q *Queries) FindAllResources(ctx context.Context) ([]ClaimctlResource, error) {
	rows, err := q.db.Query(ctx, findAllResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimctlResource
	for rows.Next() {
		var i ClaimctlResource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Labels,
			&i.Properties,
			&i.SpaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsUnderMaintenance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findResourceById = `-- name: FindResourceById :one
SELECT id, name, type, labels, properties, space_id, created_at, updated_at, is_under_maintenance FROM claimctl.resources WHERE id=$1
`

func (q *Queries) FindResourceById(ctx context.Context, id uuid.UUID) (ClaimctlResource, error) {
	row := q.db.QueryRow(ctx, findResourceById, id)
	var i ClaimctlResource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Labels,
		&i.Properties,
		&i.SpaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsUnderMaintenance,
	)
	return i, err
}

const findResourceByName = `-- name: FindResourceByName :one
SELECT id, name, type, labels, properties, space_id, created_at, updated_at, is_under_maintenance FROM claimctl.resources WHERE name=$1
`

func (q *Queries) FindResourceByName(ctx context.Context, name string) (ClaimctlResource, error) {
	row := q.db.QueryRow(ctx, findResourceByName, name)
	var i ClaimctlResource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Labels,
		&i.Properties,
		&i.SpaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsUnderMaintenance,
	)
	return i, err
}

const getAllResourcesWithReservationStatus = `-- name: GetAllResourcesWithReservationStatus :many
SELECT
    r.id,
    r.name,
    r.type,
    r.labels,
    r.space_id,
    r.created_at,
    r.updated_at,
    r.properties,
    r.is_under_maintenance,
    COALESCE(active_reservations.count, 0) as active_reservations,
    COALESCE(pending_reservations.count, 0) as queue_length,
    COALESCE(next_reservation.user_id, '00000000-0000-0000-0000-000000000000'::uuid) as next_user_id,
    COALESCE(next_reservation.queue_position, 0) as next_queue_position,
    active_res_details.start_time as active_reservation_start_time,
    active_res_details.duration as active_reservation_duration,
    active_res_details.created_at as active_reservation_created_at
FROM claimctl.resources r
LEFT JOIN (
    SELECT resource_id, COUNT(*) as count
    FROM claimctl.reservations
    WHERE status = 'active'
    GROUP BY resource_id
) active_reservations ON r.id = active_reservations.resource_id
LEFT JOIN (
    SELECT resource_id, COUNT(*) as count
    FROM claimctl.reservations
    WHERE status = 'pending'
    GROUP BY resource_id
) pending_reservations ON r.id = pending_reservations.resource_id
LEFT JOIN (
    SELECT resource_id, user_id, queue_position
    FROM claimctl.reservations
    WHERE status = 'pending' AND queue_position = 1
) next_reservation ON r.id = next_reservation.resource_id
LEFT JOIN claimctl.reservations active_res_details
  ON r.id = active_res_details.resource_id AND active_res_details.status = 'active'
`

type GetAllResourcesWithReservationStatusRow struct {
	ID                         uuid.UUID        `json:"id"`
	Name                       string           `json:"name"`
	Type                       string           `json:"type"`
	Labels                     types.JSONBArray `json:"labels"`
	SpaceID                    uuid.UUID        `json:"spaceId"`
	CreatedAt                  pgtype.Int8      `json:"createdAt"`
	UpdatedAt                  pgtype.Int8      `json:"updatedAt"`
	Properties                 types.JSONBMap   `json:"properties"`
	IsUnderMaintenance         pgtype.Bool      `json:"isUnderMaintenance"`
	ActiveReservations         int64            `json:"activeReservations"`
	QueueLength                int64            `json:"queueLength"`
	NextUserID                 uuid.UUID        `json:"nextUserId"`
	NextQueuePosition          int32            `json:"nextQueuePosition"`
	ActiveReservationStartTime pgtype.Int8      `json:"activeReservationStartTime"`
	ActiveReservationDuration  pgtype.Interval  `json:"activeReservationDuration"`
	ActiveReservationCreatedAt pgtype.Int8      `json:"activeReservationCreatedAt"`
}

func (q *Queries) GetAllResourcesWithReservationStatus(ctx context.Context) ([]GetAllResourcesWithReservationStatusRow, error) {
	rows, err := q.db.Query(ctx, getAllResourcesWithReservationStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllResourcesWithReservationStatusRow
	for rows.Next() {
		var i GetAllResourcesWithReservationStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Labels,
			&i.SpaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Properties,
			&i.IsUnderMaintenance,
			&i.ActiveReservations,
			&i.QueueLength,
			&i.NextUserID,
			&i.NextQueuePosition,
			&i.ActiveReservationStartTime,
			&i.ActiveReservationDuration,
			&i.ActiveReservationCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllResourcesWithReservationStatusForUser = `-- name: GetAllResourcesWithReservationStatusForUser :many
SELECT DISTINCT
    r.id,
    r.name,
    r.type,
    r.labels,
    r.space_id,
    r.created_at,
    r.updated_at,
    r.properties,
    r.is_under_maintenance,
    COALESCE(active_reservations.count, 0) as active_reservations,
    COALESCE(pending_reservations.count, 0) as queue_length,
    COALESCE(next_reservation.user_id, '00000000-0000-0000-0000-000000000000'::uuid) as next_user_id,
    COALESCE(next_reservation.queue_position, 0) as next_queue_position,
    active_res_details.start_time as active_reservation_start_time,
    active_res_details.duration as active_reservation_duration,
    active_res_details.created_at as active_reservation_created_at
FROM claimctl.resources r
JOIN claimctl.spaces s ON r.space_id = s.id
LEFT JOIN claimctl.space_permissions sp ON s.id = sp.space_id
LEFT JOIN claimctl.group_members gm ON sp.group_id = gm.group_id
LEFT JOIN (
    SELECT resource_id, COUNT(*) as count
    FROM claimctl.reservations
    WHERE status = 'active'
    GROUP BY resource_id
) active_reservations ON r.id = active_reservations.resource_id
LEFT JOIN (
    SELECT resource_id, COUNT(*) as count
    FROM claimctl.reservations
    WHERE status = 'pending'
    GROUP BY resource_id
) pending_reservations ON r.id = pending_reservations.resource_id
LEFT JOIN (
    SELECT resource_id, user_id, queue_position
    FROM claimctl.reservations
    WHERE status = 'pending' AND queue_position = 1
) next_reservation ON r.id = next_reservation.resource_id
LEFT JOIN claimctl.reservations active_res_details
  ON r.id = active_res_details.resource_id AND active_res_details.status = 'active'
WHERE
    s.name = 'Default Space' OR
    sp.user_id = $1 OR
    (sp.group_id IS NOT NULL AND gm.user_id = $1)
ORDER BY r.id
`

type GetAllResourcesWithReservationStatusForUserRow struct {
	ID                         uuid.UUID        `json:"id"`
	Name                       string           `json:"name"`
	Type                       string           `json:"type"`
	Labels                     types.JSONBArray `json:"labels"`
	SpaceID                    uuid.UUID        `json:"spaceId"`
	CreatedAt                  pgtype.Int8      `json:"createdAt"`
	UpdatedAt                  pgtype.Int8      `json:"updatedAt"`
	Properties                 types.JSONBMap   `json:"properties"`
	IsUnderMaintenance         pgtype.Bool      `json:"isUnderMaintenance"`
	ActiveReservations         int64            `json:"activeReservations"`
	QueueLength                int64            `json:"queueLength"`
	NextUserID                 uuid.UUID        `json:"nextUserId"`
	NextQueuePosition          int32            `json:"nextQueuePosition"`
	ActiveReservationStartTime pgtype.Int8      `json:"activeReservationStartTime"`
	ActiveReservationDuration  pgtype.Interval  `json:"activeReservationDuration"`
	ActiveReservationCreatedAt pgtype.Int8      `json:"activeReservationCreatedAt"`
}

func (q *Queries) GetAllResourcesWithReservationStatusForUser(ctx context.Context, userID pgtype.UUID) ([]GetAllResourcesWithReservationStatusForUserRow, error) {
	rows, err := q.db.Query(ctx, getAllResourcesWithReservationStatusForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllResourcesWithReservationStatusForUserRow
	for rows.Next() {
		var i GetAllResourcesWithReservationStatusForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Labels,
			&i.SpaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Properties,
			&i.IsUnderMaintenance,
			&i.ActiveReservations,
			&i.QueueLength,
			&i.NextUserID,
			&i.NextQueuePosition,
			&i.ActiveReservationStartTime,
			&i.ActiveReservationDuration,
			&i.ActiveReservationCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaintenanceHistory = `-- name: GetMaintenanceHistory :many
SELECT
    mal.id, mal.resource_id, mal.previous_state, mal.new_state, mal.changed_by, mal.changed_at, mal.reason,
    u.email as changed_by_email
FROM claimctl.maintenance_audit_log mal
JOIN claimctl.users u ON mal.changed_by = u.id
WHERE mal.resource_id = $1
ORDER BY mal.changed_at DESC
`

type GetMaintenanceHistoryRow struct {
	ID             uuid.UUID   `json:"id"`
	ResourceID     uuid.UUID   `json:"resourceId"`
	PreviousState  bool        `json:"previousState"`
	NewState       bool        `json:"newState"`
	ChangedBy      uuid.UUID   `json:"changedBy"`
	ChangedAt      pgtype.Int8 `json:"changedAt"`
	Reason         pgtype.Text `json:"reason"`
	ChangedByEmail string      `json:"changedByEmail"`
}

func (q *Queries) GetMaintenanceHistory(ctx context.Context, resourceID uuid.UUID) ([]GetMaintenanceHistoryRow, error) {
	rows, err := q.db.Query(ctx, getMaintenanceHistory, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMaintenanceHistoryRow
	for rows.Next() {
		var i GetMaintenanceHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.PreviousState,
			&i.NewState,
			&i.ChangedBy,
			&i.ChangedAt,
			&i.Reason,
			&i.ChangedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourceMaintenanceStatus = `-- name: GetResourceMaintenanceStatus :one
SELECT is_under_maintenance FROM claimctl.resources WHERE id = $1
`

func (q *Queries) GetResourceMaintenanceStatus(ctx context.Context, id uuid.UUID) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, getResourceMaintenanceStatus, id)
	var is_under_maintenance pgtype.Bool
	err := row.Scan(&is_under_maintenance)
	return is_under_maintenance, err
}

const getResourceName = `-- name: GetResourceName :one
SELECT name FROM claimctl.resources WHERE id = $1
`

func (q *Queries) GetResourceName(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getResourceName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getResourceReservationStatus = `-- name: GetResourceReservationStatus :one
SELECT
    r.id,
    r.name,
    r.type,
    r.labels,
    r.space_id,
    r.created_at,
    r.updated_at,
    r.properties,
    r.is_under_maintenance,
    COALESCE(active_reservations.count, 0) as active_reservations,
    COALESCE(pending_reservations.count, 0) as queue_length,
    COALESCE(next_reservation.user_id, '00000000-0000-0000-0000-000000000000'::uuid) as next_user_id,
    COALESCE(next_reservation.queue_position, 0) as next_queue_position,
    active_res_details.start_time as active_reservation_start_time,
    active_res_details.duration as active_reservation_duration,
    active_res_details.created_at as active_reservation_created_at
FROM claimctl.resources r
LEFT JOIN (
    SELECT resource_id, COUNT(*) as count
    FROM claimctl.reservations
    WHERE status = 'active'
    GROUP BY resource_id
) active_reservations ON r.id = active_reservations.resource_id
LEFT JOIN (
    SELECT resource_id, COUNT(*) as count
    FROM claimctl.reservations
    WHERE status = 'pending'
    GROUP BY resource_id
) pending_reservations ON r.id = pending_reservations.resource_id
LEFT JOIN (
    SELECT resource_id, user_id, queue_position
    FROM claimctl.reservations
    WHERE status = 'pending' AND queue_position = 1
) next_reservation ON r.id = next_reservation.resource_id
LEFT JOIN claimctl.reservations active_res_details
  ON r.id = active_res_details.resource_id AND active_res_details.status = 'active'
WHERE r.id = $1
`

type GetResourceReservationStatusRow struct {
	ID                         uuid.UUID        `json:"id"`
	Name                       string           `json:"name"`
	Type                       string           `json:"type"`
	Labels                     types.JSONBArray `json:"labels"`
	SpaceID                    uuid.UUID        `json:"spaceId"`
	CreatedAt                  pgtype.Int8      `json:"createdAt"`
	UpdatedAt                  pgtype.Int8      `json:"updatedAt"`
	Properties                 types.JSONBMap   `json:"properties"`
	IsUnderMaintenance         pgtype.Bool      `json:"isUnderMaintenance"`
	ActiveReservations         int64            `json:"activeReservations"`
	QueueLength                int64            `json:"queueLength"`
	NextUserID                 uuid.UUID        `json:"nextUserId"`
	NextQueuePosition          int32            `json:"nextQueuePosition"`
	ActiveReservationStartTime pgtype.Int8      `json:"activeReservationStartTime"`
	ActiveReservationDuration  pgtype.Interval  `json:"activeReservationDuration"`
	ActiveReservationCreatedAt pgtype.Int8      `json:"activeReservationCreatedAt"`
}

func (q *Queries) GetResourceReservationStatus(ctx context.Context, id uuid.UUID) (GetResourceReservationStatusRow, error) {
	row := q.db.QueryRow(ctx, getResourceReservationStatus, id)
	var i GetResourceReservationStatusRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Labels,
		&i.SpaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Properties,
		&i.IsUnderMaintenance,
		&i.ActiveReservations,
		&i.QueueLength,
		&i.NextUserID,
		&i.NextQueuePosition,
		&i.ActiveReservationStartTime,
		&i.ActiveReservationDuration,
		&i.ActiveReservationCreatedAt,
	)
	return i, err
}

const getResourceTest = `-- name: GetResourceTest :one
SELECT id, name FROM claimctl.resources WHERE id=$1
`

type GetResourceTestRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) GetResourceTest(ctx context.Context, id uuid.UUID) (GetResourceTestRow, error) {
	row := q.db.QueryRow(ctx, getResourceTest, id)
	var i GetResourceTestRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const logMaintenanceChange = `-- name: LogMaintenanceChange :one
INSERT INTO claimctl.maintenance_audit_log (resource_id, previous_state, new_state, changed_by, reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, resource_id, previous_state, new_state, changed_by, changed_at, reason
`

type LogMaintenanceChangeParams struct {
	ResourceID    uuid.UUID   `json:"resourceId"`
	PreviousState bool        `json:"previousState"`
	NewState      bool        `json:"newState"`
	ChangedBy     uuid.UUID   `json:"changedBy"`
	Reason        pgtype.Text `json:"reason"`
}

func (q *Queries) LogMaintenanceChange(ctx context.Context, arg LogMaintenanceChangeParams) (ClaimctlMaintenanceAuditLog, error) {
	row := q.db.QueryRow(ctx, logMaintenanceChange,
		arg.ResourceID,
		arg.PreviousState,
		arg.NewState,
		arg.ChangedBy,
		arg.Reason,
	)
	var i ClaimctlMaintenanceAuditLog
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.PreviousState,
		&i.NewState,
		&i.ChangedBy,
		&i.ChangedAt,
		&i.Reason,
	)
	return i, err
}

const setResourceMaintenanceMode = `-- name: SetResourceMaintenanceMode :one
UPDATE claimctl.resources
SET is_under_maintenance = $2, updated_at = $3
WHERE id = $1
RETURNING id, name, type, labels, properties, space_id, created_at, updated_at, is_under_maintenance
`

type SetResourceMaintenanceModeParams struct {
	ID                 uuid.UUID   `json:"id"`
	IsUnderMaintenance pgtype.Bool `json:"isUnderMaintenance"`
	UpdatedAt          pgtype.Int8 `json:"updatedAt"`
}

func (q *Queries) SetResourceMaintenanceMode(ctx context.Context, arg SetResourceMaintenanceModeParams) (ClaimctlResource, error) {
	row := q.db.QueryRow(ctx, setResourceMaintenanceMode, arg.ID, arg.IsUnderMaintenance, arg.UpdatedAt)
	var i ClaimctlResource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Labels,
		&i.Properties,
		&i.SpaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsUnderMaintenance,
	)
	return i, err
}

const updateResourceById = `-- name: UpdateResourceById :exec
UPDATE claimctl.resources SET name=$1, labels=$2, type=$3, properties=$4
WHERE id=$5
`

type UpdateResourceByIdParams struct {
	Name       string           `json:"name"`
	Labels     types.JSONBArray `json:"labels"`
	Type       string           `json:"type"`
	Properties types.JSONBMap   `json:"properties"`
	ID         uuid.UUID        `json:"id"`
}

func (q *Queries) UpdateResourceById(ctx context.Context, arg UpdateResourceByIdParams) error {
	_, err := q.db.Exec(ctx, updateResourceById,
		arg.Name,
		arg.Labels,
		arg.Type,
		arg.Properties,
		arg.ID,
	)
	return err
}

const verifyResourceNameIsUnique = `-- name: VerifyResourceNameIsUnique :one
SELECT COUNT(*) FROM claimctl.resources WHERE name=$1
`

func (q *Queries) VerifyResourceNameIsUnique(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, verifyResourceNameIsUnique, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}
