// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: resource_webhooks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addResourceWebhook = `-- name: AddResourceWebhook :exec
INSERT INTO claimctl.resource_webhooks (
    resource_id, webhook_id, events
) VALUES (
    $1, $2, $3
) ON CONFLICT (resource_id, webhook_id) DO UPDATE
SET events = $3
`

type AddResourceWebhookParams struct {
	ResourceID uuid.UUID `json:"resourceId"`
	WebhookID  uuid.UUID `json:"webhookId"`
	Events     []string  `json:"events"`
}

func (q *Queries) AddResourceWebhook(ctx context.Context, arg AddResourceWebhookParams) error {
	_, err := q.db.Exec(ctx, addResourceWebhook, arg.ResourceID, arg.WebhookID, arg.Events)
	return err
}

const getResourceWebhooks = `-- name: GetResourceWebhooks :many
SELECT w.id, w.name, w.url, w.method, w.headers, w.template, w.description, w.signing_secret, w.created_at, w.updated_at, rw.events
FROM claimctl.webhooks w
JOIN claimctl.resource_webhooks rw ON w.id = rw.webhook_id
WHERE rw.resource_id = $1
`

type GetResourceWebhooksRow struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	Url           string      `json:"url"`
	Method        string      `json:"method"`
	Headers       []byte      `json:"headers"`
	Template      pgtype.Text `json:"template"`
	Description   pgtype.Text `json:"description"`
	SigningSecret string      `json:"signingSecret"`
	CreatedAt     pgtype.Int8 `json:"createdAt"`
	UpdatedAt     pgtype.Int8 `json:"updatedAt"`
	Events        []string    `json:"events"`
}

func (q *Queries) GetResourceWebhooks(ctx context.Context, resourceID uuid.UUID) ([]GetResourceWebhooksRow, error) {
	rows, err := q.db.Query(ctx, getResourceWebhooks, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResourceWebhooksRow
	for rows.Next() {
		var i GetResourceWebhooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Method,
			&i.Headers,
			&i.Template,
			&i.Description,
			&i.SigningSecret,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Events,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebhooksForEvent = `-- name: GetWebhooksForEvent :many
SELECT w.id, w.name, w.url, w.method, w.headers, w.template, w.description, w.signing_secret, w.created_at, w.updated_at
FROM claimctl.webhooks w
JOIN claimctl.resource_webhooks rw ON w.id = rw.webhook_id
WHERE rw.resource_id = $1 AND $2::text = ANY(rw.events)
`

type GetWebhooksForEventParams struct {
	ResourceID uuid.UUID `json:"resourceId"`
	Column2    string    `json:"column2"`
}

func (q *Queries) GetWebhooksForEvent(ctx context.Context, arg GetWebhooksForEventParams) ([]ClaimctlWebhook, error) {
	rows, err := q.db.Query(ctx, getWebhooksForEvent, arg.ResourceID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimctlWebhook
	for rows.Next() {
		var i ClaimctlWebhook
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Method,
			&i.Headers,
			&i.Template,
			&i.Description,
			&i.SigningSecret,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeResourceWebhook = `-- name: RemoveResourceWebhook :exec
DELETE FROM claimctl.resource_webhooks
WHERE resource_id = $1 AND webhook_id = $2
`

type RemoveResourceWebhookParams struct {
	ResourceID uuid.UUID `json:"resourceId"`
	WebhookID  uuid.UUID `json:"webhookId"`
}

func (q *Queries) RemoveResourceWebhook(ctx context.Context, arg RemoveResourceWebhookParams) error {
	_, err := q.db.Exec(ctx, removeResourceWebhook, arg.ResourceID, arg.WebhookID)
	return err
}
