// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: secrets.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSecret = `-- name: CreateSecret :one
INSERT INTO claimctl.secrets (
    key, value, description
) VALUES (
    $1, $2, $3
) RETURNING id, key, value, description, created_at, updated_at
`

type CreateSecretParams struct {
	Key         string      `json:"key"`
	Value       string      `json:"value"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (ClaimctlSecret, error) {
	row := q.db.QueryRow(ctx, createSecret, arg.Key, arg.Value, arg.Description)
	var i ClaimctlSecret
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSecret = `-- name: DeleteSecret :exec
DELETE FROM claimctl.secrets
WHERE id = $1
`

func (q *Queries) DeleteSecret(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSecret, id)
	return err
}

const getSecret = `-- name: GetSecret :one
SELECT id, key, value, description, created_at, updated_at FROM claimctl.secrets
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSecret(ctx context.Context, id uuid.UUID) (ClaimctlSecret, error) {
	row := q.db.QueryRow(ctx, getSecret, id)
	var i ClaimctlSecret
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSecretByKey = `-- name: GetSecretByKey :one
SELECT id, key, value, description, created_at, updated_at FROM claimctl.secrets
WHERE key = $1 LIMIT 1
`

func (q *Queries) GetSecretByKey(ctx context.Context, key string) (ClaimctlSecret, error) {
	row := q.db.QueryRow(ctx, getSecretByKey, key)
	var i ClaimctlSecret
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSecrets = `-- name: ListSecrets :many
SELECT id, key, value, description, created_at, updated_at FROM claimctl.secrets
ORDER BY key
`

func (q *Queries) ListSecrets(ctx context.Context) ([]ClaimctlSecret, error) {
	rows, err := q.db.Query(ctx, listSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimctlSecret
	for rows.Next() {
		var i ClaimctlSecret
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Value,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSecret = `-- name: UpdateSecret :one
UPDATE claimctl.secrets
SET value = $2,
    description = $3,
    updated_at = EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT
WHERE id = $1
RETURNING id, key, value, description, created_at, updated_at
`

type UpdateSecretParams struct {
	ID          uuid.UUID   `json:"id"`
	Value       string      `json:"value"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateSecret(ctx context.Context, arg UpdateSecretParams) (ClaimctlSecret, error) {
	row := q.db.QueryRow(ctx, updateSecret, arg.ID, arg.Value, arg.Description)
	var i ClaimctlSecret
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
