// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSetting = `-- name: GetSetting :one
SELECT key, value, category, description, is_secret, updated_at FROM app_settings
WHERE key = $1 LIMIT 1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (AppSetting, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i AppSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Category,
		&i.Description,
		&i.IsSecret,
		&i.UpdatedAt,
	)
	return i, err
}

const getSettings = `-- name: GetSettings :many
SELECT key, value, category, description, is_secret, updated_at FROM app_settings
ORDER BY category, key
`

func (q *Queries) GetSettings(ctx context.Context) ([]AppSetting, error) {
	rows, err := q.db.Query(ctx, getSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppSetting
	for rows.Next() {
		var i AppSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Category,
			&i.Description,
			&i.IsSecret,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :one
INSERT INTO app_settings (key, value, category, description, is_secret, updated_at)
VALUES ($1, $2, $3, $4, $5, CURRENT_TIMESTAMP)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    category = EXCLUDED.category,
    description = EXCLUDED.description,
    is_secret = EXCLUDED.is_secret,
    updated_at = CURRENT_TIMESTAMP
RETURNING key, value, category, description, is_secret, updated_at
`

type UpsertSettingParams struct {
	Key         string      `json:"key"`
	Value       string      `json:"value"`
	Category    string      `json:"category"`
	Description pgtype.Text `json:"description"`
	IsSecret    bool        `json:"isSecret"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) (AppSetting, error) {
	row := q.db.QueryRow(ctx, upsertSetting,
		arg.Key,
		arg.Value,
		arg.Category,
		arg.Description,
		arg.IsSecret,
	)
	var i AppSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Category,
		&i.Description,
		&i.IsSecret,
		&i.UpdatedAt,
	)
	return i, err
}
