// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: spaces.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSpace = `-- name: CreateSpace :one
INSERT INTO claimctl.spaces (name, description)
VALUES ($1, $2)
RETURNING id, name, description, created_at, updated_at
`

type CreateSpaceParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) (ClaimctlSpace, error) {
	row := q.db.QueryRow(ctx, createSpace, arg.Name, arg.Description)
	var i ClaimctlSpace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSpace = `-- name: DeleteSpace :exec
DELETE FROM claimctl.spaces WHERE id = $1
`

func (q *Queries) DeleteSpace(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSpace, id)
	return err
}

const getSpace = `-- name: GetSpace :one
SELECT id, name, description, created_at, updated_at FROM claimctl.spaces WHERE id = $1
`

func (q *Queries) GetSpace(ctx context.Context, id uuid.UUID) (ClaimctlSpace, error) {
	row := q.db.QueryRow(ctx, getSpace, id)
	var i ClaimctlSpace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSpaceByName = `-- name: GetSpaceByName :one
SELECT id, name, description, created_at, updated_at FROM claimctl.spaces WHERE name = $1
`

func (q *Queries) GetSpaceByName(ctx context.Context, name string) (ClaimctlSpace, error) {
	row := q.db.QueryRow(ctx, getSpaceByName, name)
	var i ClaimctlSpace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasSpacePermission = `-- name: HasSpacePermission :one
SELECT EXISTS (
    SELECT 1 FROM claimctl.spaces s
    LEFT JOIN claimctl.space_permissions sp ON s.id = sp.space_id
    LEFT JOIN claimctl.group_members gm ON sp.group_id = gm.group_id
    WHERE s.id = $1 AND (
        s.name = 'Default Space' OR
        sp.user_id = $2 OR
        (sp.group_id IS NOT NULL AND gm.user_id = $2)
    )
)
`

type HasSpacePermissionParams struct {
	ID     uuid.UUID   `json:"id"`
	UserID pgtype.UUID `json:"userId"`
}

func (q *Queries) HasSpacePermission(ctx context.Context, arg HasSpacePermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasSpacePermission, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listSpaces = `-- name: ListSpaces :many
SELECT id, name, description, created_at, updated_at FROM claimctl.spaces ORDER BY id
`

func (q *Queries) ListSpaces(ctx context.Context) ([]ClaimctlSpace, error) {
	rows, err := q.db.Query(ctx, listSpaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimctlSpace
	for rows.Next() {
		var i ClaimctlSpace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpacesForUser = `-- name: ListSpacesForUser :many
SELECT DISTINCT s.id, s.name, s.description, s.created_at, s.updated_at
FROM claimctl.spaces s
LEFT JOIN claimctl.space_permissions sp ON s.id = sp.space_id
LEFT JOIN claimctl.group_members gm ON sp.group_id = gm.group_id
WHERE
    s.name = 'Default Space' OR
    sp.user_id = $1 OR
    (sp.group_id IS NOT NULL AND gm.user_id = $1)
ORDER BY s.id
`

func (q *Queries) ListSpacesForUser(ctx context.Context, userID pgtype.UUID) ([]ClaimctlSpace, error) {
	rows, err := q.db.Query(ctx, listSpacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimctlSpace
	for rows.Next() {
		var i ClaimctlSpace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpace = `-- name: UpdateSpace :one
UPDATE claimctl.spaces
SET name = $1, description = $2, updated_at = EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT
WHERE id = $3
RETURNING id, name, description, created_at, updated_at
`

type UpdateSpaceParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateSpace(ctx context.Context, arg UpdateSpaceParams) (ClaimctlSpace, error) {
	row := q.db.QueryRow(ctx, updateSpace, arg.Name, arg.Description, arg.ID)
	var i ClaimctlSpace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
