// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users_config.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const updateUserChannelConfig = `-- name: UpdateUserChannelConfig :one
UPDATE claimctl.users
SET slack_destination = $2, teams_webhook_url = $3, notification_email = $4
WHERE id = $1
RETURNING id, email, name, password, created_at, updated_at, role, status, last_login, failed_login_attempts, locked_until, slack_destination, teams_webhook_url, notification_email
`

type UpdateUserChannelConfigParams struct {
	ID                uuid.UUID   `json:"id"`
	SlackDestination  pgtype.Text `json:"slackDestination"`
	TeamsWebhookUrl   pgtype.Text `json:"teamsWebhookUrl"`
	NotificationEmail pgtype.Text `json:"notificationEmail"`
}

func (q *Queries) UpdateUserChannelConfig(ctx context.Context, arg UpdateUserChannelConfigParams) (ClaimctlUser, error) {
	row := q.db.QueryRow(ctx, updateUserChannelConfig,
		arg.ID,
		arg.SlackDestination,
		arg.TeamsWebhookUrl,
		arg.NotificationEmail,
	)
	var i ClaimctlUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.Status,
		&i.LastLogin,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.SlackDestination,
		&i.TeamsWebhookUrl,
		&i.NotificationEmail,
	)
	return i, err
}
