// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT COUNT(*) FROM claimctl.users WHERE role = 'admin'
`

func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO claimctl.users (email, name, password, role, status, last_login) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateUserParams struct {
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	Password  string             `json:"password"`
	Role      string             `json:"role"`
	Status    string             `json:"status"`
	LastLogin pgtype.Timestamptz `json:"lastLogin"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.Password,
		arg.Role,
		arg.Status,
		arg.LastLogin,
	)
	return err
}

const deleteUserById = `-- name: DeleteUserById :exec
DELETE FROM claimctl.users WHERE id=$1
`

func (q *Queries) DeleteUserById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserById, id)
	return err
}

const findAllUsers = `-- name: FindAllUsers :many
SELECT id, email, name, password, created_at, updated_at, role, status, last_login, failed_login_attempts, locked_until, slack_destination, teams_webhook_url, notification_email FROM claimctl.users
`

func (q *Queries) FindAllUsers(ctx context.Context) ([]ClaimctlUser, error) {
	rows, err := q.db.Query(ctx, findAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimctlUser
	for rows.Next() {
		var i ClaimctlUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.Status,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.SlackDestination,
			&i.TeamsWebhookUrl,
			&i.NotificationEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, name, password, created_at, updated_at, role, status, last_login, failed_login_attempts, locked_until, slack_destination, teams_webhook_url, notification_email FROM claimctl.users WHERE email=$1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (ClaimctlUser, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i ClaimctlUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.Status,
		&i.LastLogin,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.SlackDestination,
		&i.TeamsWebhookUrl,
		&i.NotificationEmail,
	)
	return i, err
}

const findUserById = `-- name: FindUserById :one
SELECT id, email, name, password, created_at, updated_at, role, status, last_login, failed_login_attempts, locked_until, slack_destination, teams_webhook_url, notification_email FROM claimctl.users WHERE id=$1
`

func (q *Queries) FindUserById(ctx context.Context, id uuid.UUID) (ClaimctlUser, error) {
	row := q.db.QueryRow(ctx, findUserById, id)
	var i ClaimctlUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.Status,
		&i.LastLogin,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.SlackDestination,
		&i.TeamsWebhookUrl,
		&i.NotificationEmail,
	)
	return i, err
}

const getPasswordById = `-- name: GetPasswordById :one
SELECT password FROM claimctl.users WHERE id=$1
`

func (q *Queries) GetPasswordById(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getPasswordById, id)
	var password string
	err := row.Scan(&password)
	return password, err
}

const resetUserFailedLoginAttempts = `-- name: ResetUserFailedLoginAttempts :exec
UPDATE claimctl.users
SET failed_login_attempts = 0, locked_until = NULL
WHERE id = $1
`

func (q *Queries) ResetUserFailedLoginAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetUserFailedLoginAttempts, id)
	return err
}

const updateUserById = `-- name: UpdateUserById :exec
UPDATE claimctl.users SET email=$1, name=$2, password=$3, role=$4, status=$5, last_login=$6, updated_at=CURRENT_TIMESTAMP
WHERE id=$7
`

type UpdateUserByIdParams struct {
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	Password  string             `json:"password"`
	Role      string             `json:"role"`
	Status    string             `json:"status"`
	LastLogin pgtype.Timestamptz `json:"lastLogin"`
	ID        uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateUserById(ctx context.Context, arg UpdateUserByIdParams) error {
	_, err := q.db.Exec(ctx, updateUserById,
		arg.Email,
		arg.Name,
		arg.Password,
		arg.Role,
		arg.Status,
		arg.LastLogin,
		arg.ID,
	)
	return err
}

const updateUserFailedLoginAttempts = `-- name: UpdateUserFailedLoginAttempts :one
UPDATE claimctl.users
SET failed_login_attempts = failed_login_attempts + 1, locked_until = $1
WHERE id = $2
RETURNING failed_login_attempts
`

type UpdateUserFailedLoginAttemptsParams struct {
	LockedUntil pgtype.Timestamptz `json:"lockedUntil"`
	ID          uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateUserFailedLoginAttempts(ctx context.Context, arg UpdateUserFailedLoginAttemptsParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateUserFailedLoginAttempts, arg.LockedUntil, arg.ID)
	var failed_login_attempts int32
	err := row.Scan(&failed_login_attempts)
	return failed_login_attempts, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE claimctl.users SET last_login=CURRENT_TIMESTAMP WHERE id=$1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE claimctl.users
SET password = $1
WHERE id = $2
`

type UpdateUserPasswordParams struct {
	Password string    `json:"password"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.Password, arg.ID)
	return err
}

const verifyUserEmailIsUnique = `-- name: VerifyUserEmailIsUnique :one
SELECT COUNT(*) FROM claimctl.users where email=$1
`

func (q *Queries) VerifyUserEmailIsUnique(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRow(ctx, verifyUserEmailIsUnique, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}
