// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: webhooks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO claimctl.webhooks (
    name, url, method, headers, template, description, signing_secret
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, name, url, method, headers, template, description, signing_secret, created_at, updated_at
`

type CreateWebhookParams struct {
	Name          string      `json:"name"`
	Url           string      `json:"url"`
	Method        string      `json:"method"`
	Headers       []byte      `json:"headers"`
	Template      pgtype.Text `json:"template"`
	Description   pgtype.Text `json:"description"`
	SigningSecret string      `json:"signingSecret"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (ClaimctlWebhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.Name,
		arg.Url,
		arg.Method,
		arg.Headers,
		arg.Template,
		arg.Description,
		arg.SigningSecret,
	)
	var i ClaimctlWebhook
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Method,
		&i.Headers,
		&i.Template,
		&i.Description,
		&i.SigningSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM claimctl.webhooks
WHERE id = $1
`

func (q *Queries) DeleteWebhook(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWebhook, id)
	return err
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, name, url, method, headers, template, description, signing_secret, created_at, updated_at FROM claimctl.webhooks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWebhook(ctx context.Context, id uuid.UUID) (ClaimctlWebhook, error) {
	row := q.db.QueryRow(ctx, getWebhook, id)
	var i ClaimctlWebhook
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Method,
		&i.Headers,
		&i.Template,
		&i.Description,
		&i.SigningSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, name, url, method, headers, template, description, signing_secret, created_at, updated_at FROM claimctl.webhooks
ORDER BY name
`

func (q *Queries) ListWebhooks(ctx context.Context) ([]ClaimctlWebhook, error) {
	rows, err := q.db.Query(ctx, listWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimctlWebhook
	for rows.Next() {
		var i ClaimctlWebhook
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Method,
			&i.Headers,
			&i.Template,
			&i.Description,
			&i.SigningSecret,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE claimctl.webhooks
SET name = $2,
    url = $3,
    method = $4,
    headers = $5,
    template = $6,
    description = $7,
    updated_at = EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT
WHERE id = $1
RETURNING id, name, url, method, headers, template, description, signing_secret, created_at, updated_at
`

type UpdateWebhookParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Url         string      `json:"url"`
	Method      string      `json:"method"`
	Headers     []byte      `json:"headers"`
	Template    pgtype.Text `json:"template"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (ClaimctlWebhook, error) {
	row := q.db.QueryRow(ctx, updateWebhook,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.Method,
		arg.Headers,
		arg.Template,
		arg.Description,
	)
	var i ClaimctlWebhook
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Method,
		&i.Headers,
		&i.Template,
		&i.Description,
		&i.SigningSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
