// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: webhook_logs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupOldWebhookLogs = `-- name: CleanupOldWebhookLogs :exec
DELETE FROM claimctl.webhook_logs
WHERE created_at < $1
`

func (q *Queries) CleanupOldWebhookLogs(ctx context.Context, createdAt pgtype.Timestamp) error {
	_, err := q.db.Exec(ctx, cleanupOldWebhookLogs, createdAt)
	return err
}

const createWebhookLog = `-- name: CreateWebhookLog :one
INSERT INTO claimctl.webhook_logs (
  webhook_id, event, status_code, request_body, response_body, duration_ms
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, webhook_id, event, status_code, request_body, response_body, duration_ms, created_at
`

type CreateWebhookLogParams struct {
	WebhookID    uuid.UUID `json:"webhookId"`
	Event        string    `json:"event"`
	StatusCode   int32     `json:"statusCode"`
	RequestBody  string    `json:"requestBody"`
	ResponseBody string    `json:"responseBody"`
	DurationMs   int32     `json:"durationMs"`
}

func (q *Queries) CreateWebhookLog(ctx context.Context, arg CreateWebhookLogParams) (ClaimctlWebhookLog, error) {
	row := q.db.QueryRow(ctx, createWebhookLog,
		arg.WebhookID,
		arg.Event,
		arg.StatusCode,
		arg.RequestBody,
		arg.ResponseBody,
		arg.DurationMs,
	)
	var i ClaimctlWebhookLog
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.Event,
		&i.StatusCode,
		&i.RequestBody,
		&i.ResponseBody,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const getWebhookLogs = `-- name: GetWebhookLogs :many
SELECT id, webhook_id, event, status_code, request_body, response_body, duration_ms, created_at FROM claimctl.webhook_logs
WHERE webhook_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetWebhookLogsParams struct {
	WebhookID uuid.UUID `json:"webhookId"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) GetWebhookLogs(ctx context.Context, arg GetWebhookLogsParams) ([]ClaimctlWebhookLog, error) {
	rows, err := q.db.Query(ctx, getWebhookLogs, arg.WebhookID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimctlWebhookLog
	for rows.Next() {
		var i ClaimctlWebhookLog
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.Event,
			&i.StatusCode,
			&i.RequestBody,
			&i.ResponseBody,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
